### ISSUE TITLE
Unable to compile Erlang/OTP 20.1 on MacOSX Mojave

### ISSUE THREAD

**Issue by devjoaoGustavo** [asdf-vm/asdf-erlang#101]
Maybe someone could help me with this problem. When installing any erlang/opt version on my machine, the follow error appears. I couldn't find the reason:
```
joao.paula root_app_dir (master) $ kerl build 20.1 20.1
Verifying archive checksum...
Checksum verified (4c9eb112cd0e55f17c474218825060ee)
Building Erlang/OTP 20.1 (20.1), please wait...
Build failed.
In file included from wxe_impl.cpp:39:
In file included from ./wxe_gl.h:24:
./egl_impl.h:35:11: fatal error: 'GL/glu.h' file not found
# include <GL/glu.h>
          ^~~~~~~~~~
1 error generated.
make[3]: *** [x86_64-apple-darwin18.5.0/wxe_impl.o] Error 1
make[2]: *** [opt] Error 2
make[1]: *** [opt] Error 2
make: *** [libs] Error 2
```
I am using a `MacOSX 10.14.4` and `kerl 1.8.5`.

Thank you for the help

If some information is missing, please let me know.

**Comment by kenseii** [comment]
Hello, did you find any solution for this issue?
I am facing it setting up nerves.

Thanks

**Comment by tompesman** [comment]
I've solved this problem by uninstalling and reinstalling brew and asdf.

**Comment by Stratus3D** [comment]
I'm on OSX 10.14.6 using kerl 1.8.5 and I have not encountered this issue. Were you able to get it working @devjoaoGustavo ?

**Comment by devjoaoGustavo** [comment]
I couldn't make it work properly with the wxWidgets toolkit. It would be useful in order to use the Erlang process observer.
Nonetheless, I could installed Erlang, and it it's working pretty well, even though `:observer.start` wont. 

When running `:observer.start` on `iex` I face this output:
```
09:26:35.977 [error] ERROR: Could not find 'wxe_driver.so' in: /Users/my_user_name/.asdf/installs/erlang/21.3/lib/wx-1.8.7/priv

{:error,
 {{:load_driver, 'No driver found'},
  [
    {:wxe_server, :start, 1, [file: 'wxe_server.erl', line: 65]},
    {:wx, :new, 1, [file: 'wx.erl', line: 115]},
    {:observer_wx, :init, 1, [file: 'observer_wx.erl', line: 107]},
    {:wx_object, :init_it, 6, [file: 'wx_object.erl', line: 372]},
    {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}
  ]}}
```
I'll try it again with the tip @Stratus3D has given on [issue 35](https://github.com/asdf-vm/asdf-erlang/issues/35)

Thanks

**Comment by Stratus3D** [comment]
Closing this issue since I don't think there are bugs in asdf-erlang causing this. Make sure you have the right wx library installed on your system before trying to compile Erlang with wx support.
