### ISSUE TITLE
Install hangs on 22.0.1 on Ubuntu 19.04

### ISSUE THREAD

**Issue by lasseebert** [asdf-vm/asdf-erlang#102]
* Asdf version: `v0.7.2`
* Latest asdf-erlang (3934206)
* Ubuntu 19.04
* I have installed the needed dependencies per [README](https://github.com/asdf-vm/asdf-erlang#ubuntu-and-debian)

What I did:

`asdf install erlang 22.0.1`

What happened:

Outputs:

```
➤ asdf install erlang 22.0.1
Downloading OTP-22.0.1.tar.gz to /home/pulver/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122    0   122    0     0    416      0 --:--:-- --:--:-- --:--:--   417
100 52.2M    0 52.2M    0     0  5767k      0 --:--:--  0:00:09 --:--:-- 6970k
Extracting source code
Building Erlang/OTP 22.0.1 (asdf_22.0.1), please wait...
```

It then hangs forever. Looking at the log in `.asdf/plugins/erlang/kerl-home/builds/asdf_22.0.1/otp_build_22.0.1.log` it stops pretty fast on 

```
=== Entering application ssl
make[3]: Entering directory '/home/pulver/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0.1/otp_src_22.0.1/lib/ssl/src'
 GEN    /home/pulver/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0.1/otp_src_22.0.1/lib/ssl/src/deps/ssl.d
```

Nothing more is logged.

`asdf install erlang 22.0` works fine and I have `asdf install erlang 22.0.1` working fine in older Ubuntus in docker and in CI server.

Any suggestions?

**Comment by lasseebert** [comment]
Cloning OTP 22.0.1 from Gtihub and running `./configure && make` seems to work fine.

**Comment by lasseebert** [comment]
I'm getting the same hanging behaviour when installing directly through kerl. Will create an issue there instead. Sorry for opening issue here.

**Comment by lasseebert** [comment]
Another update:

I digged around with asdf and kerl to find a solution. It turned out that kerl also hanged on 22.0 (from git, not from tarball), when run directly, but asdf could install 22.0 (just not 22.0.1).

I found this in the asdf-erlang kerl log when installing 22.0 successfully:

```
# This is the line it hangs on when installing 22.0.1
 GEN	/home/pulver/.kerl/builds/22.0/otp_src_22.0/lib/ssl/src/deps/ssl.d
asdf: No version set for command erlc
you might want to add one of the following in your .tool-versions file:

erlang 21.3.6
erlang 21.3.7
erlang 21.1
# And then the installation continues here
```

This gave me a hint. I tried to install erlang 22.0.1 by changing my .tool-versions-file to use `erlang 22.0.1` and then run `asdf install`.
I then tried changing the tool-versions back to `erlang 22.0` and then run `asdf install 22.0.1` which was installed succesfully.

So apparently erlang must be installed to install erlang?
I'm not sure why this does not work on 22.0.1, but has been working fine for all previous versions for me.

**Comment by Stratus3D** [comment]
Very strange, I'm not sure why that would be the case. I jus ran a build of Erlang `22.0` on Ubuntu 18.04 and it worked for me, but now I realize I've got another version of Erlang installed. Looking at the asdf-erlang code I do not see anything that would require an existing version of Erlang. But it's possible kerl is looking for Erlang for some reason.

**Comment by lasseebert** [comment]
Yes, I still don't have a clue why all previous versions before 22.0.1 installed without problems using the same workflow and 22.0.1 hanged during installation.

Anyway, the above workaround worked.
I also had a 22.0.1 install work as expected on a remote Ubuntu 16.04, but failed on my Ubuntu 19.04. Perhaps it is just something weird going on on my local machine.
