### ISSUE TITLE
asdf list-all erlang uses wrong order on linux

### ISSUE THREAD

**Issue by axelson** [asdf-vm/asdf-erlang#103]
I apologize if this is not the correct place to report this. But I'd expect to always see the same output from list-all erlang on any platform. Instead this is the behavior I see:

Mac OS X:
```
$ asdf list-all erlang |tail
21.3.8
21.3.8.1
21.3.8.2
21.3.8.3
22.0
22.0-rc1
22.0-rc2
22.0-rc3
22.0.1
22.0.2
```

Linux (Ubuntu server):
```
$ asdf list-all erlang | tail
21.3.8
21.3.8.1
21.3.8.2
21.3.8.3
22.0
22.0-rc1
22.0-rc2
22.0-rc3
22.0.1
22.0.2
```

Updated Linux (Ubuntu server list):
```
asdf list-all erlang | tail
21.3.8.3
21.3.8.4
22.0
22.0.1
22.0.2
22.0.3
22.0.4
22.0-rc1
22.0-rc2
22.0-rc3
```

Ideally both would look like the first list since 22.0-rc1 came out before 22.0 and 22.0.1

**Comment by Stratus3D** [comment]
Definitely something we should fix. I have not had a chance to test on Ubuntu yet and I am not sure what the issue is.

**Comment by axelson** [comment]
It looks like I might have pasted the wrong output the second time so I added a new list that shows the rc's coming after. Can you confirm that the first list is the correct order?

**Comment by Hermanverschooten** [comment]
I have a similar issue on OSX
There are 289 versions and 23.0.2 is somewhere in the middle instead of at the end.

**Comment by Stratus3D** [comment]
I believe this issue has been fixed. @axelson can you check the output now?

**Comment by axelson** [comment]
Yes, it is. Thanks!

For reference here's a snippet of what I receive from `asdf list-all erlang`:

```
22.3.4.14
22.3.4.15
23.0-rc1
23.0-rc2
23.0-rc3
23.0
23.0.1
23.0.2
23.0.3
23.0.4
23.1
23.1.1
23.1.2
23.1.3
23.1.4
23.1.5
23.2
23.2.1
23.2.2
23.2.3
23.2.4
```
