### ISSUE TITLE
Alternative ErlangVM - ErlangRT (Rust)

### ISSUE THREAD

**Issue by denegny** [asdf-vm/asdf-erlang#106]
**Please add alternative ErlangVM - ErlangRT (ErlangVM written in _Rust_)**

_Erlang Replacement Therapy. Another attempt to make Erlang runtime (BEAM emulator) in Rust. Good news: I know what to do. Bad news: I have no clue how to Rust_

- [Github ErlangRT](https://github.com/kvakvs/ErlangRT)
- [Dmytro Lytovchenko - ErlangRT, a BEAM VM reimplementation in Rust | Code BEAM STO 19](https://youtu.be/e7T6p8ynVuM)

**Comment by Stratus3D** [comment]
Thanks! This is definitely something we want, but I'm not sure if we should add it to this plugin or create a new plugin.

**Comment by denegny** [comment]
> Thanks! This is definitely something we want, but I'm not sure if we should add it to this plugin or create a new plugin.

Just add new versions of ErlangRT in your list with sorting. Highest version of ErlangVM must be on bottom (for people pleasure), look at simple made in elastic repo [asdf-elasticsearch](https://github.com/mikestephens/asdf-elasticsearch/blob/master/bin/list-all)

Onу difficulty, your repo versions update manually.. ((

But I think you'll come up with something for this because a lot of examples, see how it is implemented in Ruby

P.S [version sorter - (ruby gem)](https://github.com/github/version_sorter)

**Comment by Stratus3D** [comment]
Actually, now that I'm looking at it, the prerequisites are different, so it may be easier to do it in a separate plugin. It depends on how different the build and install logic is. It's better to have two separate plugins than one plugin with a lot of conditional logic.

**Comment by denegny** [comment]
> Actually, now that I'm looking at it, the prerequisites are different, so it may be easier to do it in a separate plugin. It depends on how different the build and install logic is. It's better to have two separate plugins than one plugin with a lot of conditional logic.

ruby on JWM & IRB - its one plugin ((

I think for customers better have one plugin

**Comment by Stratus3D** [comment]
Yes, the Ruby plugin does two things, I guess it all comes down to how complicated it is to implement. I'll have to give ErlangRT a try and see how difficult it will be to add support for it to this plugin.

**Comment by eproxus** [comment]
I vote for this to be a separate plug-in, to be honest. The Rust implementation is _very_ early and shouldn't be mixed in with normal Erlang versions. If it ever gets reasonable feature parity and stability, I would reconsider it then.

**Comment by Stratus3D** [comment]
Closing because I don't have the time to implement support for ErlangRT in this plugin, and because it doesn't appear that ErlangRT is a viable alternative to the BEAM right now.
