### ISSUE TITLE
`which erlang` can't find Erlang

### ISSUE THREAD

**Issue by ChrisBuchholz** [asdf-vm/asdf-erlang#107]
I've installed Erlang using asdf, at the end of which asdf outputtet:

```
Erlang 22.0.7 has been installed. Activate globally with:

    asdf global erlang 22.0.7

Activate locally in the current folder with:

    asdf local erlang 22.0.7
```

And I have tried running `asdf global Erlang 22.0.7` and `asdf reshim` but no matter what, Erlang is not registered. Both `which` and `asdf which` can't find it. I have also installed elixir which works just fine and as expected.

Any ideas?

**Comment by Stratus3D** [comment]
What arguments are you running `which` with? `which erlang` isn't going to work because Erlang doesn't provide an `erlang` executable. You probably want to run it with `erl` or `erlc`. `type -a erl` may also be a useful command to try.

**Comment by ChrisBuchholz** [comment]
Of course! I dunno why I didn't think of that! It seems to work as expected. Sorry to bother you!
