### ISSUE TITLE
Building warnings on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by Eiji7** [asdf-vm/asdf-erlang#108]
Hey, I just set up latest `Erlang`, but found 2 problems …

## `libopenssl-devel` vs `openssl-devel`

> WARNING: It appears a required development package 'openssl-devel' is not installed.

which comes from `~/.asdf/plugins/erlang/kerl` (lines `370`-`388`):

```bash
_rpm_is_installed() {
    rpm --quiet -q "$1" >/dev/null 2>&1
}

_check_rpm() {
    required='
openssl-devel
make
automake
autoconf
ncurses-devel
gcc
'
    for pkg in $required; do
        if ! _rpm_is_installed "$pkg"; then
            echo "WARNING: It appears a required development package '$pkg' is not installed."
        fi
    done
}
```

Let me show you my output:
```
$ rpm -q openssl-devel
pakiet openssl-devel nie jest zainstalowany
# message in Polish that such package is not installed
$ rpm -q libopenssl-devel
libopenssl-devel-1.1.1c-1.1.noarch
```

For some distributions there might be different package names which is really confusing for developers, but also such warning is really confusing to end-users.

## The `odbc` application
```
APPLICATIONS DISABLED (See: /home/…/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0.7/otp_build_22.0.7.log)
 * odbc           : ODBC library - link check failed

```

Log file:

```
…
checking for odbc in standard locations... no
checking if we can add -Werror=return-type to CFLAGS (via CFLAGS)... yes
configure: creating ./config.status
config.status: creating c_src/x86_64-unknown-linux-gnu/Makefile
configure: WARNING: No odbc library found skipping odbc
configure: WARNING: "ODBC library - header check failed"
configure: WARNING: "ODBC library - link check failed"
…
```

The problem here is that I have installed all required packages i.e. `libiodbc3`, `libltdl-devel` (provided by `libtool` package) and `unixODBC`. Most probably I have missed something, but I was looking for it and of course tried to google it, but there are not much results for openSUSE.

**Comment by Eiji7** [comment]
@Stratus3D Thanks for your reply! I'm recompiling `Erlang` now, but I can already see that `odbc` is not in list of disabled applications. The problem was that in `YaST Software Manager` I have unchecked option: `Show -devel packages F7` and I simply did not saw it. :smile:

I will create an issue on project you have linked, so this one could be closed.

**Comment by oshanz** [comment]
https://github.com/kerl/kerl/issues/323
