### ISSUE TITLE
asdf install does not add version to shims

### ISSUE THREAD

**Issue by CarefreeSlacker** [asdf-vm/asdf-erlang#109]
First of all I want to say **Thank you very much!** to you for you awesome version manager. It really helpful.

### Problem description

My _.tool-versions_ loks like      

```
erlang 19.3.6.9
ruby 2.5.1
```

I have installed versions by `asdf install`     
Running `$> erl` throws following error:   

```
asdf: No version set for command erl
you might want to add one of the following in your .tool-versions file:

erlang 20.1
erlang 20.0
erlang 19.0
```

But `$> ruby` return version:

`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]`

### Problem itself

I look into shims `~/.asdf/shims/erl` and `~/.asdf/shims/ruby` and noticed that for erlang version has not been added:

```
#!/usr/bin/env bash
# asdf-plugin: erlang 20.1
# asdf-plugin: erlang 20.0
# asdf-plugin: erlang 19.0
exec /home/carefreeslacker/.asdf/bin/asdf exec "erl" "$@"
```

```
#!/usr/bin/env bash
# asdf-plugin: ruby 2.5.1
exec /home/carefreeslacker/.asdf/bin/asdf exec "ruby" "$@"
```

### Manual solution
Removing erlang version and installing it manually with `asdf install erlang 19.3.6.9.` has been solved problem.

### Environment

**OS**: Ubuntu 16.4

**asdf version**: version: v0.7.4

**Comment by Stratus3D** [comment]
Sorry for taking so long to respond to your issue. Is this still a problem? If so, does `asdf reshim` help? I'm aware that https://github.com/asdf-vm/asdf-erlang/issues/57 may contribute to this issue, but other than that there should not be anything else causing this. In either case `asdf reshim` should fix the problem.
