### ISSUE TITLE
configure error while installing erlang 19.0

### ISSUE THREAD

**Issue by HochmanEyal** [asdf-vm/asdf-erlang#11]
I tried running

`asdf install erlang 19.0`

and the terminal started dumping a lot of lines in the form of "checking...".
and then it finished with these two lines:

> configure: error: No curses library functions found
> configure: error: /bin/bash '/tmp/erlang_build_PAvpBU/otp_src_19.0/erts/configure' failed for erts

And the erlang version was not installed

**Comment by yaBliznyk** [comment]
https://github.com/asdf-vm/asdf-erlang/pull/10/files

try check depends)))

**Comment by HochmanEyal** [comment]
worked, thank you
