### ISSUE TITLE
Multiple Erlang versions within .tool-versions not supported. 

### ISSUE THREAD

**Issue by supernintendo** [asdf-vm/asdf-erlang#114]
Calling `asdf install` with the following `.tool-versions` file results in the error `22.0.7 21.3 is not a valid Erlang/OTP release`:

```
erlang 22.0.7 21.3
elixir 1.9.1 1.8.1-otp-21
```

This contradicts expected behaviour defined in the [documentation](https://asdf-vm.com/#/core-configuration?id=tool-versions) for `.tool-versions`:

> Multiple versions can be set by separating them with a space. For example, to use Python 3.7.2, fallback to Python 2.7.15 and finally to the system Python, the following line can be added to .tool-versions. Example: `python 3.7.2 2.7.15 system`

It appears that it fails regardless of the Erlang versions defined. I'm using asdf v0.7.4 on Fedora 30.

**Comment by Stratus3D** [comment]
Thank you for reporting! This is definitely an issue, but it is an issue with asdf itself and not just this plugin. Please follow the discussion on https://github.com/asdf-vm/asdf/issues/540
