### ISSUE TITLE
Use local version of erlang

### ISSUE THREAD

**Issue by axelson** [asdf-vm/asdf-erlang#119]
With the Elixir plugin it is possible to do:

```
# After Elixir already installed into /path/to/elixir
asdf local elixir path:/path/to/elixir
```

Is there something similar for the erlang plugin? I tried it but I got `asdf: No version set for command erl` so it doesn't seem to currently work.

**Comment by Stratus3D** [comment]
Yes, the same syntax is available for all plugins so `asdf local erlang path:/path/to/other/erlang` is what you would use. Right now there is a bug that seems to prevent it from being used. See https://github.com/asdf-vm/asdf/issues/559 for the discussion.

**Comment by axelson** [comment]
Okay, will follow that bug :)
