### ISSUE TITLE
Ubuntu Upstart broken

### ISSUE THREAD

**Issue by ivanovv** [asdf-vm/asdf-erlang#124]
I have a Phoenix app with an Upstart script that looks like this:

```
description "phoenix_app"

setuid deploy
setgid deploy
start on runlevel [2345]
stop on runlevel [016]
respawn limit 10 5

env LANG=en_US
export LANG

env LC_ALL=en_US.UTF-8
export LC_ALL

env MIX_ENV=prod
export MIX_ENV

env HOME=/u/apps/phoenix_app
export HOME

script
  cd /u/apps/phoenix_app
  exec ./bin/app foreground
end script
```

I've saved that file to `/u/apps/phoenix_app/phoenix.conf` and then added it to `init` with 
```
sudo ln -s /u/apps/phoenix_app/phoenix.conf /etc/init/
sudo initctl reload-configuration
```

Trying to start it with `sudo initctl start phoenix` works fine.

Trying to start it with `sudo service phoenix start` fails with a very cryptic error message:

```
Mar 21 03:36:49 dev2 run_erl[13957]: errno=2 'No such file or directory'#012Can't access log directory '/home/deploy/.asdf/installs/erlang/21.3.3/log'
```

I went ahead and created that directory to see what the app will write there.
```
cat /home/deploy/.asdf/installs/erlang/21.3.3/log/run_erl.log
run_erl [2508] Sat Mar 21 15:59:55 2020
Args before exec of shell:
run_erl [2508] Sat Mar 21 15:59:55 2020
argv[0] = sh
run_erl [2508] Sat Mar 21 15:59:55 2020
argv[1] = -c
run_erl [2508] Sat Mar 21 15:59:55 2020
argv[2] = exec /home/deploy/.asdf/installs/erlang/21.3.3/bin/start_erl /home/deploy/.asdf/installs/erlang/21.3.3 /home/deploy/.asdf/installs/erlang/21.3.3/releases phoenix
```

Looks nothing like what I expect, it should be more like 
```
cat /u/apps/phoenix_app/var/log/run_erl.log
run_erl [30247] Sat Mar 21 15:06:19 2020
Args before exec of shell:
run_erl [30247] Sat Mar 21 15:06:19 2020
argv[0] = sh
run_erl [30247] Sat Mar 21 15:06:19 2020
argv[1] = -c
run_erl [30247] Sat Mar 21 15:06:19 2020
argv[2] = exec "/u/apps/phoenix_app/bin/webinargeek" "console" --
```

Finally, I've started checking files and it turns out that `start` that `/usr/sbin/service` calls is replaced by `/home/deploy/.asdf/shims/start`
```
deploy@dev2:/u/apps/phoenix_app/var/log$ which start
/home/deploy/.asdf/shims/start
deploy@dev2:/u/apps/phoenix_app/var/log$ which stop
/sbin/stop

deploy@dev2:/u/apps/phoenix_app/var/log$ cat `which start`
#!/usr/bin/env bash
# asdf-plugin: erlang 21.3.3
exec /home/deploy/.asdf/bin/asdf exec "start" "$@"
```

Once I've deleted that `start` file, the service starts gain just fine

**Comment by Stratus3D** [comment]
> ```
> ...
> argv[0] = sh
> run_erl [2508] Sat Mar 21 15:59:55 2020
> argv[1] = -c
> run_erl [2508] Sat Mar 21 15:59:55 2020
> argv[2] = exec /home/deploy/.asdf/installs/erlang/21.3.3/bin/start_erl /home/deploy/.asdf/installs/erlang/21.3.3 /home/deploy/.asdf/installs/erlang/21.3.3/releases phoenix
> ```
> Looks nothing like what I expect, it should be more like
> ```
> ...
> argv[2] = exec "/u/apps/phoenix_app/bin/webinargeek" "console" --
> ```

Why does the first log look incorrect to you? `/u/apps/phoenix_app/bin/webinargeek` would be a Bash script, so it's not going to show up in that `run_erl.log` I don't think.

> Finally, I've started checking files and it turns out that start that /usr/sbin/service calls is replaced by /home/deploy/.asdf/shims/start

Interesting. I need to look into that. I didn't even know Erlang had an executable named `start`.

**Comment by ivanovv** [comment]
> Why does the first log look incorrect to you? /u/apps/phoenix_app/bin/webinargeek would be a Bash script, so it's not going to show up in that run_erl.log I don't think.

Because that's how it looks when I start the service with `initctl` instead of `start`.
Another thing – I don't have `phoenix` anywhere in the upstart script. I guess it comes from the `sudo service phoenix start`

> Interesting. I need to look into that. I didn't even know Erlang had an executable named start.

Well, I guess that is not important since Ubuntu moved to `systemd`, but still – I had a pretty frustrating night trying to figure this one out. So maybe we can keep the issue just for the reference. Though I tried googling and it doesn't show up yet.

**Comment by Stratus3D** [comment]
I guess I never noticed, but sure enough every Erlang installation does have a executable named `start` in the installation's `bin` directory. So asdf is creating a shim for it and putting it on your path like it should.

**Comment by Stratus3D** [comment]
Closing since I see a good way for asdf-erlang to fix this. Ideally Erlang should rename this executable to something more unique.
