### ISSUE TITLE
Unable to install 10.15.3

### ISSUE THREAD

**Issue by BWheatie** [asdf-vm/asdf-erlang#129]
Something happened today, seemingly after a brew update that caused my entire Elixir dev env to error out. I have searched this, kerl, openssl, and Elixir Forum for some solutions and tried all but the nuclear option(resetting my whole dev env). Initially I was getting no :crypto module errors. I reinstalled erlang only for no version to install. I also reinstalled asdf and openssl. 

I attempted to install many versions with no success. I believe I was initially on 22.0.7.

I am, admittedly, desperate at this point as I cannot develop until this is resolved so any help would be much much appreciated.

OSX 10.15.3

```
$ asdf install erlang 22.1.8
Downloading OTP-22.1.8.tar.gz to /Users/benwheat/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    429      0 --:--:-- --:--:-- --:--:--   429
100 52.4M    0 52.4M    0     0  5174k      0 --:--:--  0:00:10 --:--:-- 4039k
Extracting source code
Building Erlang/OTP 22.1.8 (asdf_22.1.8), please wait...
DOCUMENTATION INFORMATION (See: /Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_build_22.1.8.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.
gmake[4]: *** [x86_64-apple-darwin19.3.0/Makefile:812: /Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/bin/x86_64-apple-darwin19.3.0/erl_child_setup] Error 1
gmake[4]: *** Waiting for unfinished jobs....
gmake[4]: Leaving directory '/Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/erts/emulator'
gmake[3]: *** [/Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/erts/emulator'
gmake[2]: *** [Makefile:45: opt] Error 2
gmake[2]: Leaving directory '/Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/erts'
gmake[1]: *** [Makefile:54: smp] Error 2
gmake[1]: Leaving directory '/Users/benwheat/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.8/otp_src_22.1.8/erts'
gmake: *** [Makefile:488: emulator] Error 2```

**Comment by kpanic** [comment]
See https://github.com/erlang/otp/pull/2577

**Comment by kpanic** [comment]
Temporary workaround:

* `asdf install erlang ref:maint`
* `asdf global erlang ref:maint`

**Comment by BWheatie** [comment]
Thanks a ton!

Any ideas how this would have happened? I haven't had a problem until the brew update yesterday.

**Comment by kpanic** [comment]
@BWheatie not sure!
Looks like it was a weird update (brew upgrade, macosx, xcode, etc) combo

**Comment by lorenzosinisi** [comment]
What @kpanic says or also https://github.com/asdf-vm/asdf-erlang/issues/82#issuecomment-589965823 👍

**Comment by Stratus3D** [comment]
See https://github.com/asdf-vm/asdf-erlang/issues/116

**Comment by BWheatie** [comment]
Thanks, all. The odd thing in all of this is that I have been on this setup for months. When I brew update brew upgrade last week, this came tumbling down on me.

**Comment by devansjo** [comment]
Another workaround is to downgrade your xcode installation. Just uninstall and then install a previous version from Apple's [developer portal](https://developer.apple.com/download/more/?name=Xcode)

**Comment by jstoobz** [comment]
Great catch! I was just stumbling across this issue for the past hour or so myself.
