### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Hir0Pr0tag0nist** [asdf-vm/asdf-erlang#130]
When I try to install Erlang via asdf I get a (for me) cryptic error message that I haven't been to google up on successfully.

Build failed.
GEN obj/x86_64-apple-darwin19.4.0/opt/MADE
LD	/Users/\*\*\*\*\*\*/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.5/otp_src_22.1.5/bin/x86_64-apple-darwin19.4.0/erl_child_setup
ld: weak import of symbol '___darwin_check_fd_set_overflow' not supported because of option: -no_weak_imports for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [/Users/\*\*\*\*\*\*/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.5/otp_src_22.1.5/bin/x86_64-apple-darwin19.4.0/erl_child_setup] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

I followed the install guide and any additional resources I could find.

I'll gladly take any hints towards a solution.

**Comment by Stratus3D** [comment]
See https://github.com/kerl/kerl/issues/335

**Comment by Hir0Pr0tag0nist** [comment]
Thanks!
