### ISSUE TITLE
asdf global erlang {version} doesn't seem to activate erlang

### ISSUE THREAD

**Issue by BlueHatbRit** [asdf-vm/asdf-erlang#132]
I migrated from kerl + exenv to asdf on one of my machines a couple of weeks ago and it's been great so far, I've just moved my work laptop today and it seems the final `asdf global erlang 22.3` command isn't activating the install and means that `erl --version` is just returning saying it cannot find the command erl.

I don't believe this was a problem a few weeks ago although I admit I can't totally remember and I'm not sure what version asdf-erlang is being used on that machine.

I knew kerl was used under the hood so in the end I ran `. /Users/elliot.blackburn/.asdf/installs/erlang/22.3/activate` by hand and it worked just fine but I'm concerned there might be a bug in asdf-erlang causing it to not properly call activate when the asdf global command is issued.

I'm still quite fresh to asdf and can't see a way to find the asdf-erlang version, is there anyway I can provide some more info to help debug this and figure out if it's a problem with my machine or asdf-erlang?

**Comment by BlueHatbRit** [comment]
Sorry this was my fault, I forgot to source asdf after installing it with homebrew, silly me!

**Comment by Stratus3D** [comment]
Glad you got it sorted out. I'm not aware of any oustanding issues that would contribute to something like this.

**Comment by BlueHatbRit** [comment]
You're quite right, the entire problem was I had not sourced asdf after I'd installed it with homebrew and so the `asdf global erlang {version}` wasn't doing anything because the code was not loaded into the environment. Sorry for the bother!
