### ISSUE TITLE
OpenSuSE issue on versions > 22.3

### ISSUE THREAD

**Issue by k-cross** [asdf-vm/asdf-erlang#138]
From Erlang versions 22.3.1 and up I run into the following warning.

```
Extracting source code
mv: cannot move './otp-OTP-22.3.3' to '/home/owl/.asdf/plugins/erlang/kerl-home/builds/asdf_22.3.3/otp_src_22.3.3/otp-OTP-22.3.3': Directory not empty
Building Erlang/OTP 22.3.3 (asdf_22.3.3), please wait...
WARNING: It appears a required development package 'openssl-devel' is not installed.
```

However it is installed and thus may just not be a supported target? After it begins, it hangs here. I have yet to run any kind of trace but if you'd like me to just let me know what's most useful.

```
Loading repository data...
Reading installed packages...

S  | Name                  | Summary                                               | Type
---+-----------------------+-------------------------------------------------------+--------
i+ | libopenssl-devel      | Include Files and Libraries mandatory for Development | package
```
Let me know if you need additional info, I realize this may be a bit vague.

Also, thank you!

**Comment by Stratus3D** [comment]
asdf-erlang uses https://github.com/kerl/kerl underneath. You may find similar issues in the kerl issue tracker. Right now I don't have time to dedicate to fixing this.

**Comment by Stratus3D** [comment]
@k-cross is there anything we can do to address this in asdf-erlang? It's not clear to me that this is caused by anything in asdf-erlang.

**Comment by k-cross** [comment]
I think this is safe to close @Stratus3D  no one else seems to have an issue and I can't test it currently. Thank you for looking into it all the same.
