### ISSUE TITLE
Unable to recover from failed Erlang 23.0 installation

### ISSUE THREAD

**Issue by axelson** [asdf-vm/asdf-erlang#143]
I ran into #141 earlier, which means I ran `asdf install erlang 23.0` before #142 was merged/pulled.

But the problem I'm seeing now is:
```
jason@jdesktop ~/config (arch-desktop)> asdf install erlang 23.0
Downloading kerl...
There's already a build named asdf_23.0
jason@jdesktop ~/config (arch-desktop) [1]> asdf uninstall erlang 23.0
No such version
jason@jdesktop ~/config (arch-desktop) [1]> asdf install erlang 23.0
There's already a build named asdf_23.0
```

So instead I had to manually remove 23.0 from `~/.asdf/plugins/erlang/kerl-home/otp_installations` and `~/.asdf/plugins/erlang/kerl-home/otp_builds`. So it seems like there is a bug in the build is treated as successful too early. Also it might be good for `asdf uninstall erlang 23.0` to remove 23.0 from the `otp_installations` and `otp_builds` directories even if 23.0 was not fully installed.

I also had to remove `~/.asdf/plugins/erlang/kerl-home/archives/OTP-23.0.tar.gz` to get the build to start working.

**Comment by axelson** [comment]
Also that install ended up failing as well

**Comment by brucify** [comment]
I have same issue here:
```
$ asdf install erlang 23.0
There's already a build named asdf_23.0

$ asdf uninstall erlang 23.0
No such version
```
My install seems to have finished the kerl part but failed at `ln: ./erl_call: File exists`:
```
$ asdf install erlang 23.0
Downloading OTP-23.0.tar.gz to /Users/bruce.yinhe/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120  100   120    0     0    369      0 --:--:-- --:--:-- --:--:--   369
100 53.7M    0 53.7M    0     0  3672k      0 --:--:--  0:00:14 --:--:-- 2573k
Extracting source code
Building Erlang/OTP 23.0 (asdf_23.0), please wait...
Erlang/OTP 23.0 (asdf_23.0) has been successfully built
Installing Erlang/OTP 23.0 (asdf_23.0) in /Users/bruce.yinhe/.asdf/installs/erlang/23.0...
You can activate this installation running the following command:
. /Users/bruce.yinhe/.asdf/installs/erlang/23.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
Cleaning up compilation products for
Cleaned up compilation products for  under /Users/bruce.yinhe/.asdf/plugins/erlang/kerl-home/builds
ln: ./erl_call: File exists
```

**Comment by fahrinh** [comment]
Try this.
- remove line with '23'-thing in :
  - `~/.asdf/plugins/erlang/kerl-home/otp_installations`
  - `~/.asdf/plugins/erlang/kerl-home/otp_builds`
- `asdf plugin update --all`
- `asdf install erlang 23.0`

Success message:
```
$ asdf install erlang 23.0
Extracting source code
Building Erlang/OTP 23.0 (asdf_23.0), please wait...
Erlang/OTP 23.0 (asdf_23.0) has been successfully built
Installing Erlang/OTP 23.0 (asdf_23.0) in /Users/fahrinh/.asdf/installs/erlang/23.0...
You can activate this installation running the following command:
. /Users/fahrinh/.asdf/installs/erlang/23.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
Cleaning up compilation products for
Cleaned up compilation products for  under /Users/fahrinh/.asdf/plugins/erlang/kerl-home/builds
ln: ./erl_call: File exists

Erlang 23.0 has been installed. Activate globally with:

    asdf global erlang 23.0

Activate locally in the current folder with:

    asdf local erlang 23.0
```

**Comment by phpcitizen** [comment]
My installation gets stuck here:
Building Erlang/OTP 23.0 (asdf_23.0), please wait...

**Comment by Stratus3D** [comment]
@phpcitizen how long did you wait for it to install? It may take 30 minutes or more on some systems. Check your CPU usage.

**Comment by phpcitizen** [comment]
@Stratus3D I think I waited more than 30 minutes, let it go for a while...

I tried it on WSL Ubuntu, did not check CPU, will check.

**Comment by jthegedus** [comment]
Possibly related https://github.com/asdf-vm/asdf/issues/724

**Comment by Stratus3D** [comment]
https://github.com/asdf-vm/asdf-erlang/pull/145 should fix this.

**Comment by kupkovski** [comment]
following the steps pointed by @fahrinh worked for me!
Thank you guys

**Comment by reddy-1025** [comment]
I am getting this error for 23.2 version.
APPLICATIONS INFORMATION (See: /home/reddy/.asdf/plugins/erlang/kerl-home/builds/asdf_23.2/otp_build_23.2.log)
 * wx             : wxWidgets was not compiled with --enable-compat28, wx will NOT be useable
 * Can not link the wx driver, wx will NOT be useable
