### ISSUE TITLE
build failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by v3470** [asdf-vm/asdf-erlang#144]
I tried both version 23.0 and 22.0 of erlang, and before that any deps of ` build-essential autoconf m4 libncurses5-dev libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop` has been installed and `KERL_CONFIGURE_OPTIONS` set to `--disable-debug --without-javac` as the README said.

after run `asdf install erlang 22.0` a few time, it failed with following logs:

```
Building Erlang/OTP 22.0 (asdf_22.0), please wait...
Configure options have changed. Reconfiguring...
APPLICATIONS DISABLED (See: /home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_build_22.0.log)
 * jinterface     : No Java compiler found

DOCUMENTATION INFORMATION (See: /home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_build_22.0.log)
 * documentation  : 
 *                  xmllint is missing.
 *                  Using fakefop to generate placeholder PDF files.

Build failed.
make[3]: *** [x86_64-unknown-linux-gnu/wxe_funcs.o] Error 1
make[3]: Leaving directory '/home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_src_22.0/lib/wx/c_src'
/home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_src_22.0/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[2]: *** [opt] Error 2
make[2]: Leaving directory '/home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_src_22.0/lib/wx'
/home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_src_22.0/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[1]: *** [opt] Error 2
make[1]: Leaving directory '/home/user/.asdf/plugins/erlang/kerl-home/builds/asdf_22.0/otp_src_22.0/lib'
Makefile:490: recipe for target 'libs' failed
make: *** [libs] Error 2
```

I have no idea about how to fix it. The local version of erlang is 20.

**Comment by Stratus3D** [comment]
Not sure. Are you using the latest version of asdf-erlang? `asdf plugin-update erlang`.

**Comment by v3470** [comment]
@Stratus3D I checked version and Yes it is the latest version. Maybe I should try to using kerl first.

**Comment by v3470** [comment]
@Stratus3D After I tried on `kerl` I found the problem is that the virtual memory was not enough. Change the swap size and compile done. It was strange that `asdf` didn't provide anymore detail except a `Error 1`.

**Comment by Stratus3D** [comment]
@v3470 was kerl able to provide more information about the error?

**Comment by v3470** [comment]
@Stratus3D yes. There was a line information following the the line of `Error 1`

**Comment by Stratus3D** [comment]
Did you have to do anything to get kerl to show you that output?

**Comment by v3470** [comment]
@Stratus3D just enter `kerl build 22.3.4`. The error msg of the virtual memory didn't output at console, but been written in the kerl's build log file. I checked asdf-erlang's build log file before, it didn't show that virtual memory was no enough.

**Comment by v3470** [comment]
@Stratus3D sorry I make a stupid mistake. recheck the asdf-erlang log file I found a similar error info about memory. my fault

**Comment by Stratus3D** [comment]
@v3470 no worries. Glad there was a message in the log about it.
