### ISSUE TITLE
Not able to install erlang otp 22.x

### ISSUE THREAD

**Issue by siddhant3030** [asdf-vm/asdf-erlang#160]
I'm trying to install erlang otp 22.x. I have installed elixir and erlang using asdf and I have set the global version as otp 23 and elixir latest. But one for one of my projects I need to install otp 22 but It somehow not able to install and I’m getting this error.

`asdf_22.1.7 is not a kerl-managed Erlang/OTP installation
The asdf_22.1.7 build has been deleted
Extracting source code
Building Erlang/OTP 22.1.7 (asdf_22.1.7), please wait...
Build failed.
                             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/netinet6/in6.h:212:30: note: previous declaration is here
extern const struct in6_addr in6addr_loopback;
                             ^
2 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/socket_nif.o] Error 1
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Please see /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log for full details.`

I don't know what is causing this. Do I have to uninstall the erlang version which I have installed?

any suggestions on this?

**Comment by Stratus3D** [comment]
What do you see in `/Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log`? That probably has information you can use to figure out what the problem is.

**Comment by Stratus3D** [comment]
What OS version are you running on? Are you sure you've installed all the dependencies?

**Comment by siddhant3030** [comment]
I'm using macOS Catalina 10.15.6. 

I followed these steps 

1. installed asdf using brew install asdf
2. asdf plugin-add erlang
3. asdf install erlang 22.1.8

**Comment by siddhant3030** [comment]
`▶ brew install asdf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
command-tab-plus                                                                                                                virtualhostx

==> Downloading https://github.com/asdf-vm/asdf/archive/v0.7.8.tar.gz
Already downloaded: /Users/siddhant/Library/Caches/Homebrew/downloads/34d73b51ece171e6c4ffe51147d4599c5b7f78749b379dec98ab7dd9174bd595--asdf-0.7.8.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/asdf/0.7.8: 104 files, 219.6KB, built in 2 seconds

~
▶ asdf plugin-add erlang
initializing plugin repository...
Cloning into '/Users/siddhant/.asdf/repository'...
remote: Enumerating objects: 2224, done.
remote: Total 2224 (delta 0), reused 0 (delta 0), pack-reused 2224
Receiving objects: 100% (2224/2224), 502.74 KiB | 624.00 KiB/s, done.
Resolving deltas: 100% (1000/1000), done.

~
▶ asdf install erlang 22.1.7
Downloading kerl...
asdf_22.1.7 is not a kerl-managed Erlang/OTP installation
No build named asdf_22.1.7
Downloading OTP-22.1.7.tar.gz to /Users/siddhant/.asdf/plugins/erlang/kerl-home/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   122  100   122    0     0    261      0 --:--:-- --:--:-- --:--:--   261
100 52.4M    0 52.4M    0     0  7499k      0 --:--:--  0:00:07 --:--:-- 8890k
Extracting source code
Building Erlang/OTP 22.1.7 (asdf_22.1.7), please wait...
Build failed.
                             ^
 CC	obj/x86_64-apple-darwin19.6.0/opt/smp/prim_file_nif.o
 CC	obj/x86_64-apple-darwin19.6.0/opt/smp/zlib_nif.o
2 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/inet_drv.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Please see /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log for full details.

~                                                                                                                                                                                                                                                           ⍉
▶ /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log for full details.
zsh: permission denied: /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log

~                                                                                                                                                                                                                                                           ⍉
▶ /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log
zsh: permission denied: /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log

~                                                                                                                                                                                                                                                           ⍉
▶ /Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7

kerl-home/builds/asdf_22.1.7  master ✔                                                                                                                                                                                                                63d4h
▶ ls
otp_build_22.1.7.log otp_src_22.1.7`

**Comment by siddhant3030** [comment]
Above is the list of things I did and in the last, I get the same error every time. If you see if I go to this 
/Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log for full details.

Not sure what to do there?

**Comment by siddhant3030** [comment]
Also I'm using this plugin which is suggested here 

https://github.com/asdf-vm/asdf-erlang

**Comment by siddhant3030** [comment]
Also, Autoconf and wxmac is also installed.

**Comment by siddhant3030** [comment]
this is the gist for this file when I go into this 

/Users/siddhant/.asdf/plugins/erlang/kerl-home/builds/asdf_22.1.7/otp_build_22.1.7.log for full details.

https://gist.github.com/siddhant3030/f210dac84164765dcd5858d215b2d736

**Comment by Stratus3D** [comment]
The first error I see in that file is `./configure: line 4833: -L/usr/local/lib: No such file or directory`. I am not sure what that means. Have you modified your library paths on your system?

**Comment by siddhant3030** [comment]
No, I haven't changed anything. But how can I fix it?

**Comment by Stratus3D** [comment]
Are you certain you have installed all the dependencies? I've not encountered this issue before.

**Comment by siddhant3030** [comment]
Yes, I had installed all the dependencies but in order to make it work, I had to reinstall the macOS again. Then I followed the same method but this time I made sure that before compiling any erlang I will install all the dependencies carefully. Now it is working. But I wanted to know about the error? I don't understand the error and what is related to it?

**Comment by Stratus3D** [comment]
I don't know either about the error. My guess is either a dependency was not installed correctly or something caused the Erlang build to get misconfigured.

**Comment by siddhant3030** [comment]
Okay, I'm closing this issue. Thank you for taking a look

**Comment by ospaarmann** [comment]
I had the same issues and none of the suggestions worked. This did the trick for me (via https://github.com/asdf-vm/asdf-erlang/issues/116#issuecomment-538678768):

> asdf-erlang has been updated to use kerl version 1.8.6. Can you try updating asdf-erlang and see if that fixes the problem? asdf plugin-update erlang should do the trick.

- Delete archive of failed build from ~/.asdf/plugins/erlang/kerl-home/archives (not sure if this is necessary though)
- `asdf plugin-update erlang`
- `asdf install erlang 22.3.4.12`
