### ISSUE TITLE
Build fails on macOS 10.15.7

### ISSUE THREAD

**Issue by sicksid** [asdf-vm/asdf-erlang#167]
Hey guys, im trying to install erlang but it keeps failing, this is what i have in case you can give me some help:

tried the following env variable changes:

`export KERL_CONFIGURE_OPTIONS="--without-javac --without-hipe --with-ssl=$(brew --prefix openssl)"` 
`export CFLAGS="-O2 -g -fno-stack-check`

But nothing seems to help at all, I also have Xcode 12 installed and that may have something to do with this, the main error I get from the logs is: 

```
:: error: 85                                                         _Nonnull '__IPHONE_OS_VERSION_MIN_REQUIRED' is not defined, evaluates to 0 [-Werror,-Wundef]:/usr/local/include/signal.h
```

which seems to be Xcode related, or something like that

```
asdf_22.3.1 is not a kerl-managed Erlang/OTP installation
The asdf_22.3.1 build has been deleted
Extracting source code
Building Erlang/OTP 22.3.1 (asdf_22.3.1), please wait...
APPLICATIONS DISABLED (See: /Users/me/.asdf/plugins/erlang/kerl-home/builds/asdf_22.3.1/otp_build_22.3.1.log)
 * jinterface     : Java compiler disabled by user

Build failed.
216 warnings and 4 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/erl_alloc.o] Error 1
216 warnings and 4 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/erl_process.o] Error 1
216 warnings and 4 errors generated.
make[4]: *** [obj/x86_64-apple-darwin19.6.0/opt/smp/beam_emu.o] Error 1
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2

Please see /Users/me/.asdf/plugins/erlang/kerl-home/builds/asdf_22.3.1/otp_build_22.3.1.log for full details.
```

[otp_build_22.3.1.log](https://github.com/asdf-vm/asdf-erlang/files/5325018/otp_build_22.3.1.log)

**Comment by miguelcoba** [comment]
I could make it work for macos 10.15.7 and erlang 22.3.4.11

MacOS Catalina 10.15.7 includes new clang version 12 that is more picky in compiling things, so I compiled using the gcc 10 from brew.

# For MacOS 10.15.7
brew install gcc

export KERL_CONFIGURE_OPTIONS="--disable-hipe --without-javac --with-ssl=$(brew --prefix openssl)"                             
export CFLAGS="-O2 -g -fno-stack-check"
export CC=/usr/local/bin/gcc-10 

asdf install erlang 22.3.4.11

Hope it helps

**Comment by sicksid** [comment]
Hey, @miguelcoba thank you very much for your answer, I managed to get it working although I tried a couple of things at the same time:

`sudo rm -rf /Library/Developer/CommandLineTools` then reinstalled with `sudo xcode-select --install` 

and `export CC=/usr/local/bin/gcc-10` which I think is what made everything work, for the other `CFLAG` and `KERL_CONFIGURE_OPTIONS` variables, those by themselves were throwing the error from above so I'm pretty sure that defining the variable `CC` is what helped

again, thank you very much it was definitively an xcode related issue as you mentioned
