### ISSUE TITLE
Issues with wxWidgets on installing erlang

### ISSUE THREAD

**Issue by r-coh** [asdf-vm/asdf-erlang#170]
I've been trying to install there newer versions of erlang ie. 23.1 and 23.1.1 on PopOs 20.04. But can't seem to get the wxWidgets working. The version specified in the docs for asdf is `libgtk3.0-gtk3-dev` which currently has no installation candidate, instead refered to as `libwxgtk3.0-gtk3-0v5` which works well and is installed from [here](https://packages.ubuntu.com/search?keywords=libwxgtk3.0-gtk3-0v5).

Even after following having this installed i still get the same problem. 
Any help resolving this is very much appreciated. :pray:

**Comment by Stratus3D** [comment]
Did you install `libwxgtk3.0-gtk3-0v5` prior to compiling Erlang on your system? You must have all dependencies installed correctly prior to running `asdf install erlang ...`.

**Comment by r-coh** [comment]
Yeah, that resolved the issue.
