### ISSUE TITLE
`asdf list-all erlang` failed on mac big sur

### ISSUE THREAD

**Issue by jacktang** [asdf-vm/asdf-erlang#174]
The environment

* Mac Big Sur
* zsh
* homebrew

I follow the guide on https://asdf-vm.com/#/core-manage-asdf?id=install . asdf is installed and when I run `asdf list-all erlang` it did not download kerl. The logs shown below

```
> $ asdf list-all erlang                                
Downloading kerl...
chmod: /Users/jack/.asdf/plugins/erlang/kerl: No such file or directory
/Users/jack/.asdf/plugins/erlang/bin/utils.sh: line 44: /Users/jack/.asdf/plugins/erlang/kerl: No such file or directory
/Users/jack/.asdf/plugins/erlang/bin/list-all: line 8: /Users/jack/.asdf/plugins/erlang/kerl: No such file or directory
```

When I linked the kerl file manually, the command would remove the file.

**Comment by Stratus3D** [comment]
@jacktang sorry for the late response here! Did you try upgrading to the latest version of asdf-erlang? `asdf plugin-update erlang`. I do remember we had a bug in our kerl-installing logic at some point a while back. It would delete all versions of kerl that weren't correct and failed to recognize the right version of curl when it downloaded it.

**Comment by linjunpop** [comment]
Same issue when curl failed to download the kerl (https://github.com/asdf-vm/asdf-erlang/blob/e99a10615b047b963d3ce9ac28d84b2c9889c390/bin/utils.sh#L38)

Resolved with a stable network environment.
