### ISSUE TITLE
Installing on Ubuntu LTS 20.04.1 fails after "Downloading kerl"

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [asdf-vm/asdf-erlang#182]
Background
----

I have Ubuntu and I am trying to install erlang 22.2.8 via this asdf plugin.

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

Problem
----

In fact, I want to install any version of erlang, but none works.

```
$ asdf install erlang 22.2.8
Downloading kerl...
$
```

It stops after "Downloading kerl" and then nothing happens. Its like it fnished.
I have followed the steps [before-asdf-install](https://github.com/asdf-vm/asdf-erlang#before-asdf-install) also before installing the plugin, but non the less this does not prevent the error. 

How can I fix this?

**Comment by Stratus3D** [comment]
@Fl4m3Ph03n1x what is the exit code of the `asdf install` command? If the status code is non-zero, this may be a poorly handled error. If it is zero, then this possibly a bug in the asdf-erlang install logic.

**Comment by Fl4m3Ph03n1x** [comment]
Here:

```
$ asdf install erlang 22.2.8
Downloading kerl...
$ echo $?
1
```

The exit code is 1.

**Comment by Fl4m3Ph03n1x** [comment]
I finally got a workaround working.

First I tried adding the company certificates to my ssl permissions as described in this post:
https://stackoverflow.com/questions/54402673/how-to-fix-ssl-certificate-problem-self-signed-certificate-in-certificate-chai

However, even after that, it didn't work. So I eventually decided to go with the risky option, which was to use the `~/.curlrc`.

https://ec.haxx.se/cmdline/cmdline-configfile#default-config-file

After setting up this file and adding the `-k` option in it, it worked. I can now finally install the erlang versions I need to work. 

It should be noted, **this is a risk**. In fact, **this is a workaround and not really a solution**. 

However, for the time being, I will happily take it.

I am not sure how you want to proceed with this @Stratus3D , if you feel like this merits a change in code as to make the errors more visible, I would love that.

If you think that closing the ticket is enough, I will accept the decision also. Up to you, I think my part here is done :D

**Comment by Stratus3D** [comment]
@Fl4m3Ph03n1x so state my understanding of things:

* A regular SSL connection to github fails because of an issue with ca-certificates
* Disabling SSL checking gets around this issue
* The output of asdf-erlang has been unhelpful

I agree that not checking the certificate checking is not ok, but until you get ca-certificates stuff fixed I don't see a solution to this. We can add a line of output to asdf-erlang explaining that the build failed, which should help some with the usability. We may not have any more info on why the build failed, because kerl is what is actually building Erlang.

**Comment by Stratus3D** [comment]
Could `HTTP_PROXY` or `HTTPS_PROXY` possible help with your issue?

**Comment by Fl4m3Ph03n1x** [comment]
@Stratus3D Your understanding the  situation is correct.

> We can add a line of output to asdf-erlang explaining that the build failed, which should help some with the usability. We may not have any more info on why the build failed, because kerl is what is actually building Erlang.

Adding an output error log would definitively help. At least I, as a user, would know something went wrong.
In this specific case, you could check if the `curl` command (to download kerl) succeeded or failed. In my case, the `curl` was failing. I suggest you verify the output of `curl`s and if it is != 0, then you know something went wrong. Showing the curl error would also be nice.

As for the issue, as I mentioned, I am happy with the solution I have for now. Will keep it for the time being.
It is your decision if you want to keep this issue open or not now.
