### ISSUE TITLE
Minimal installation on Ubuntu-16.04: zip requirement is missing

### ISSUE THREAD

**Issue by inikulshin** [asdf-vm/asdf-erlang#197]
https://github.com/asdf-vm/asdf-erlang#ubuntu-1604-lts-xenial-xerus

I tried to `apt-get -y install build-essential autoconf m4 libncurses5-dev libssh-dev` only (for docker image) and I couldn't make ez files without zip:
`/bin/sh: 4: zip: not found`

**Comment by Stratus3D** [comment]
Did you have to install a package for `zip`? If so, what was the package name so we can document this dependency?

**Comment by Stratus3D** [comment]
Closing due to lack of a response. If someone knows what package needs to be installed on Ubuntu 16.04 let me know.
