### ISSUE TITLE
Documentation correction for Fedora build

### ISSUE THREAD

**Issue by reza-naq** [asdf-vm/asdf-erlang#206]
Hi there,
Here's the command which installs the missing dependencies on Fedora 34:

```
sudo dnf install wxGTK wxGTK-devel wxGTK-gl wxGTK-media \
  java-11-openjdk-devel \
  libiodbc unixODBC-devel erlang-odbc
```
1) Replace `yum` by 'dnf`
2) Change the name of some packages

Spent hours to get the compilation through.
Thanks

**Comment by Stratus3D** [comment]
Hi @reza-naq , sorry for the late reply here. And thanks for providing this info! I'm looking at the current readme it looks like we group CentOS & Fedora together. As far as I know centos still uses `yum`. Do we need to have a separate section for Fedora installations?

Feel free to create a PR if what we have now is not correct for Fedora.

**Comment by Stratus3D** [comment]
Closing due to lack of a response.

**Comment by miXwui** [comment]
I just went through installation on Fedora 36 and can confirm that what's currently in the readme (even with `yum` instead of `dnf` commands) worked, except this one error:

```
Building Erlang/OTP 25.0.4 (asdf_25.0.4), please wait...
WARNING: It appears a required development package 'automake' is not installed.
...
```

After installing `automake`:

```
sudo dnf in automake
```
The build error disappeared.

***

Prior to the above (installing all of [these](https://github.com/asdf-vm/asdf-erlang#centos--fedora)  + `automake`), I did everything below which also worked:

This (though I didn't check for any extraneous dependencies):

> Hi there, Here's the command which installs the missing dependencies on Fedora 34:
> 
> ```
> sudo dnf install wxGTK wxGTK-devel wxGTK-gl wxGTK-media \
>   java-11-openjdk-devel \
>   libiodbc unixODBC-devel erlang-odbc
> ```
> 
> 1. Replace `yum` by 'dnf`
> 2. Change the name of some packages
> 
> Spent hours to get the compilation through. Thanks

Fixed these errors:

```
Building Erlang/OTP 25.0.4 (asdf_25.0.4), please wait...
APPLICATIONS DISABLED (See: /home/mwu/.asdf/plugins/erlang/kerl-home/builds/asdf_25.0.4/otp_build_25.0.4.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /home/mwu/.asdf/plugins/erlang/kerl-home/builds/asdf_25.0.4/otp_build_25.0.4.log)
...
 * wx             : No OpenGL headers found, wx will NOT be usable
 * No GLU headers found, wx will NOT be usable
 * wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
 *         wxWidgets must be installed on your system.
 *         Please check that wx-config is in path, the directory
 *         where wxWidgets libraries are installed (returned by
 *         'wx-config --libs' or 'wx-config --static --libs' command)
 *         is in LD_LIBRARY_PATH or equivalent variable and
 *         wxWidgets version is 3.0.2 or above.
```
***
To fix these errors:

```
...
Building Erlang/OTP 25.0.4 (asdf_25.0.4), please wait...
WARNING: It appears a required development package 'automake' is not installed.
WARNING: It appears a required development package 'autoconf' is not installed.
WARNING: It appears a required development package 'ncurses-devel' is not installed.
Build failed.
checking for tgetent in -lcurses... no
checking for tgetent in -ltermcap... no
checking for tgetent in -ltermlib... no
configure: error: No curses library functions found
ERROR: /home/mwu/.asdf/plugins/erlang/kerl-home/builds/asdf_25.0.4/otp_src_25.0.4/erts/configure failed!
...
```

```
sudo dnf in automake autoconf ncurses-devel
```
***
To fix this error:

```
DOCUMENTATION INFORMATION (See: /home/mwu/.asdf/plugins/erlang/kerl-home/builds/asdf_25.0.4/otp_build_25.0.4.log)
 * documentation  : 
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.
```
```
sudo dnf in libxslt fop
```

**Comment by Stratus3D** [comment]
Feel free to create a PR to update the readme @miXwui I don't know of any maintainers that use Fedora so you know more about building on Fedora than we do.

**Comment by miXwui** [comment]
Thanks for the headsup @Stratus3D!

I went to double check on a fresh Fedora 36 Live CD in a virtual machine and it seems like the instructions in fact work perfectly.

I'm not sure why I previously got the `'automake is not installed error'` error on my main machine as it should have been installed (and was in the Live CD VM) via the `'C Development Tools and Libraries'` part of `sudo yum groupinstall -y 'Development Tools' 'C Development Tools and Libraries'`.

So I don't think the readme needs to be updated, yet 😏.
