### ISSUE TITLE
Unable to install Erlang 24.0.5 on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [asdf-vm/asdf-erlang#215]
LOG:
asdf_24.0.5 is not a kerl-managed Erlang/OTP installation
The asdf_24.0.5 build has been deleted
Extracting source code
Building Erlang/OTP 24.0.5 (asdf_24.0.5), please wait...
WARNING: It appears a required development package 'openssl-devel' is not installed.
APPLICATIONS DISABLED (See: /home/leandro/.asdf/plugins/erlang/kerl-home/builds/asdf_24.0.5/otp_build_24.0.5.log)
 * odbc           : ODBC library - link check failed

APPLICATIONS INFORMATION (See: /home/leandro/.asdf/plugins/erlang/kerl-home/builds/asdf_24.0.5/otp_build_24.0.5.log)
 * wx             : wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available

DOCUMENTATION INFORMATION (See: /home/leandro/.asdf/plugins/erlang/kerl-home/builds/asdf_24.0.5/otp_build_24.0.5.log)
 * documentation  : 
 *                  fop is missing. 
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 24.0.5 (asdf_24.0.5) has been successfully built
ERROR: Installation (asdf_24.0.5) already registered for this location (/home/leandro/.asdf/installs/erlang/24.0.5)
-------------
Package openssl-devel already installed.

**Comment by Stratus3D** [comment]
I am not familiar with OpenSuse Tumbleweed, but it may be that you have to do more than install `openssl-devel` in order for the Erlang build to find it. You may need to set an environment variable or flag specifying the location of the package contents. See https://github.com/kerl/kerl#compiling-crypto-on-macs for more information.

**Comment by Stratus3D** [comment]
Closing due to lack of a response.
