### ISSUE TITLE
erl -man <module name> doesn't work

### ISSUE THREAD

**Issue by MaciekTalaska** [asdf-vm/asdf-erlang#22]
I have problem with accessing Erlang modules documentation. Typing `erl -man <modulename>` results in `No manual entry for <modulename>`

I have xsltproc and fop installed.

My OS is 64bit Ubuntu 16.04 (tried that on 16.10 as well). 

I tried to locate build logs, but with no luck.

**Comment by MaciekTalaska** [comment]
OK. I have resolved the issue: http://stackoverflow.com/a/42053208/165751

Any chance to have the build process more sophisticated, so that downloading and copying man pages takes becomes part of it?

**Comment by HashNuke** [comment]
@MaciekTalaska Yes please ~! Setting up man should be a part of the build process.

Would love contributions from anyone for this ~!

**Comment by Stratus3D** [comment]
I've got a PR out for this now!

**Comment by MaciekTalaska** [comment]
I have installed the newest version of asdf and asdf-erlang on a new machine and man pages still are missing. That's why I think this should be re-opened (or new ticket shoudl be created - should I create one?)

I haven't committed much last this, but this time... I would like to pick it up, and see if I can fix that.

**Comment by MaciekTalaska** [comment]
I have prepared a PR for this. It works on my machine ;) it passes travis build as well, but I would be more than happy if someone review the changes I have made. I am happy to discuss the code or improve things if needed. 

Please note that I don't know bash very well, so what I wrote may not be optimal.

**Comment by Stratus3D** [comment]
@MaciekTalaska thanks for looking into this. After I closed this issue we moved over to using kerl, so something may have been lost during that transition. If you have changes that fix this issue please open a PR.
