### ISSUE TITLE
Package 'libwxgtk3.0-dev' has no installation candidate 

### ISSUE THREAD

**Issue by fariasmateuss** [asdf-vm/asdf-erlang#239]
The step didn't work: 
```bash
$ sudo apt-get install libwxgtk3.0-dev

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libwxgtk3.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libwxgtk3.0-dev' has no installation candidate
```
Installation with the prebuilt packages succeeded, but required one additional dependencies:
`libwxgtk3.0-gtk3-0v5`.

**Comment by taka41s** [comment]
if u're having troubles with it u can fix using this `apt-get -y install libwxgtk3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev`

**Comment by Stratus3D** [comment]
Closing this since the package name has been updated.
