### ISSUE TITLE
Unable to install Erlang 24 on Pop_OS! (Debian based)

### ISSUE THREAD

**Issue by dkarter** [asdf-vm/asdf-erlang#243]
Thank you for this great plugin!

Ever since I started using Pop_OS! I have had an issue installing Erlang via the ASDF plugin.
I am able to install via the official erlang solutions `deb` and `apt` but not with ASDF, but that causes issues on shared projects that require ASDF.

I'm not sure what the log is complaining about here so would appreciate any advice

```
/usr/bin/ld: obj/x86_64-pc-linux-gnu/opt/jit/preload.o: warning: relocation in read-only section `.rodata'
collect2: error: ld returned 1 exit status
gmake[4]: *** [x86_64-pc-linux-gnu/Makefile:1231: /home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/bin/x86_64-pc-linux-gnu/beam.jit] Error 1
gmake[4]: Leaving directory '/home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/erts/emulator'
gmake[3]: *** [/home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/make/run_make.mk:35: opt] Error 2
gmake[3]: Leaving directory '/home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/erts/emulator'
gmake[2]: *** [Makefile:45: opt] Error 2
gmake[2]: Leaving directory '/home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/erts'
gmake[1]: *** [Makefile:54: jit] Error 2
gmake[1]: Leaving directory '/home/dorian/.asdf/plugins/erlang/kerl-home/builds/asdf_24.2/otp_src_24.2/erts'
gmake: *** [Makefile:483: emulator] Error 2
```

Full error log: https://gist.github.com/dkarter/16e97e0c7ba1ea87d1ff4c9299ab3ec1

**Comment by Stratus3D** [comment]
@dkarter I'm not sure. I've not observed that error myself. Did you verify you installed all the dependencies needed on your OS? Did you try installing Erlang 24 anywhere else?

**Comment by jc00ke** [comment]
@dkarter sorry to necropost, but did you figure something out to get it installed? I'm running into a similar place in the logs before the install script fails (though I'm using [rtx](https://github.com/jdx/rtx)).

**Comment by dkarter** [comment]
@jc00ke If I recall correctly, this was due to some other tweaks I made for macOS that were no longer needed, and caused the compilation to fail 

Check if you have these set up in your environment somewhere, then remove them and restart your shell before trying again:

https://github.com/dkarter/dotfiles/commit/7ece58c755ca077be2734461cacd4a7160aa0c08

Also here are a few other (and more recent) commits related to Erlang in my dotfiles - maybe something here will be helpful:

https://github.com/search?q=repo%3Adkarter%2Fdotfiles+erlang+&type=commits

**Comment by jc00ke** [comment]
Awesome, thanks @dkarter! It seems as though the install actually succeeded on my machine but that the install after that was failing. I'll take a look at your links and hopefully it's something in there for me as well.

**Comment by jc00ke** [comment]
I just updated to the latest rtx and I was able to install both 26.1.2 and 25.3.2.1 with no issues. :man_shrugging:
