### ISSUE TITLE
How to resolve "The requested wxWidgets build couldn't be found." ?

### ISSUE THREAD

**Issue by keshav-c** [asdf-vm/asdf-erlang#244]
While installing erlang 24.3.2, I get the following errors

```
APPLICATIONS INFORMATION (See: /home/keshav/.asdf/plugins/erlang/kerl-home/builds/asdf_24.3.2/otp_build_24.3.2.log)
 * wx             : 
 *     The requested wxWidgets build couldn't be found.
 *     
 *     The configuration you asked for  requires a wxWidgets
 *     build with the following settings:
 *         --unicode
 *     but such build is not available.
 *     To see the wxWidgets builds available on this system, please use
 *     'wx-config --list' command. To use the default build, returned by
 *     'wx-config --selected-config', use the options with their 'auto'
 *     default values.
 *     If you still get this error, then check that 'wx-config' is
 *     in path, the directory where wxWidgets libraries are installed
 *     (returned by 'wx-config --libs' command) is in LD_LIBRARY_PATH
 *     or equivalent variable and wxWidgets version is 3.0.2 or above.
 * wxWidgets was not compiled with --enable-webview or wxWebView developer package is not installed, wxWebView will NOT be available
 *         wxWidgets must be installed on your system.
 *         Please check that wx-config is in path, the directory
 *         where wxWidgets libraries are installed (returned by
 *         'wx-config --libs' or 'wx-config --static --libs' command)
 *         is in LD_LIBRARY_PATH or equivalent variable and
 *         wxWidgets version is 3.0.2 or above.

Erlang/OTP 24.3.2 (asdf_24.3.2) has been successfully built
Installing Erlang/OTP 24.3.2 (asdf_24.3.2) in /home/keshav/.asdf/installs/erlang/24.3.2...
You can activate this installation running the following command:
. /home/keshavchakravarthy/.asdf/installs/erlang/24.3.2/activate
Later on, you can leave the installation typing:
kerl_deactivate
Cleaning up compilation products for 
Cleaned up compilation products for  under /home/keshav/.asdf/plugins/erlang/kerl-home/builds
```

Prior to this step I had already installed the dependencies mentioned in the README.
I also installed the wxWidgets ubuntu packages mentioned here: https://docs.codelite.org/wxWidgets/repo315/#ubuntu-and-debian
once I got the above error.

Running `wx-config --list` gives me this message
```
    Default config is gtk3-unicode-3.1-unofficial

          No config found to match: /usr/bin/wx-config --list
          in /usr/lib/x86_64-linux-gnu/wx/config

          Please install the desired library build, or specify a different
          prefix where it may be found.  If the library is not installed
          you may call its wx-config directly by specifying its full path.


  Also available in /usr:
    base-unicode-3.0
    base-unicode-3.1-unofficial
    gtk3-unicode-3.0
    gtk3-unicode-3.1-unofficial
```

I'm trying to run all this on Ubuntu 20.04
Please help me out with this :pray:

**Comment by Stratus3D** [comment]
Hi @keshav-c , wxWidgets issues are common with Erlang builds. The page you linked to (https://docs.codelite.org/wxWidgets/repo315/#ubuntu-and-debian) lists a lot of packages for Ubuntu. Which ones did you install? 

> ```*     If you still get this error, then check that 'wx-config' is
> *     in path, the directory where wxWidgets libraries are installed
> *     (returned by 'wx-config --libs' command) is in LD_LIBRARY_PATH
> *     or equivalent variable and wxWidgets version is 3.0.2 or above.```

It seems like this is at odds with the output you pasted from `wx-config --list`. What does `wx-config --libs` output?

**Comment by keshav-c** [comment]
Hi @Stratus3D . First of all thanks for working on this project and helping me out. I really appreciate it.

I installed the packages for ubuntu focal as mentioned on the page. Here are the lines from my apt/sources.list
```
deb [arch=amd64] https://repos.codelite.org/wx3.1.5/ubuntu/ focal universe
# deb-src [arch=amd64] https://repos.codelite.org/wx3.1.5/ubuntu/ focal universe
```
I added the arch because I was getting the following error on apt update
```
N: Skipping acquire of configured file 'universe/binary-i386/Packages' as repository 'https://repos.codelite.org/wx3.1.5/ubuntu focal InRelease' doesn't support architecture 'i386'
```
As for `wx-config --libs` this is what that shows
```
          Warning: No config found to match: /usr/bin/wx-config --libs
                   in /usr/lib/x86_64-linux-gnu/wx/config
          If you require this configuration, please install the desired
          library build.  If this is part of an automated configuration
          test and no other errors occur, you may safely ignore it.
          You may use wx-config --list to see all configs available in
          the default prefix.
```
I tried reinstalling the packages, but it seems that they were installed correctly
```
libwxbase3.1-0-unofficial is already the newest version (3.1.5-1.focal).
libwxbase3.1-0-unofficial-dbg is already the newest version (3.1.5-1.focal).
libwxbase3.1unofficial-dev is already the newest version (3.1.5-1.focal).
libwxgtk-media3.1-0-unofficial is already the newest version (3.1.5-1.focal).
libwxgtk-media3.1-0-unofficial-dbg is already the newest version (3.1.5-1.focal).
libwxgtk-media3.1unofficial-dev is already the newest version (3.1.5-1.focal).
libwxgtk-webview3.1-0-unofficial is already the newest version (3.1.5-1.focal).
libwxgtk-webview3.1-0-unofficial-dbg is already the newest version (3.1.5-1.focal).
libwxgtk-webview3.1unofficial-dev is already the newest version (3.1.5-1.focal).
libwxgtk3.1-0-unofficial is already the newest version (3.1.5-1.focal).
libwxgtk3.1-0-unofficial-dbg is already the newest version (3.1.5-1.focal).
libwxgtk3.1unofficial-dev is already the newest version (3.1.5-1.focal).
wx-common is already the newest version (3.1.5-1.focal).
wx3.1-examples is already the newest version (3.1.5-1.focal).
wx3.1-headers is already the newest version (3.1.5-1.focal).
wx3.1-i18n is already the newest version (3.1.5-1.focal).
```

**Comment by keshav-c** [comment]
So after some googling I found that I need to choose the correct version of wx-config first
```
$ sudo update-alternatives --config wx-config 
There are 4 choices for the alternative wx-config (providing /usr/bin/wx-config).

  Selection    Path                                                             Priority   Status
------------------------------------------------------------
* 0            /usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.1-unofficial   318       auto mode
  1            /usr/lib/x86_64-linux-gnu/wx/config/base-unicode-3.0              306       manual mode
  2            /usr/lib/x86_64-linux-gnu/wx/config/base-unicode-3.1-unofficial   317       manual mode
  3            /usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.0              309       manual mode
  4            /usr/lib/x86_64-linux-gnu/wx/config/gtk3-unicode-3.1-unofficial   318       manual mode
```
I chose _option 3_. I don't know the reason why this works. I also had to install the package `libwxgtk-webview3.0-gtk3-dev` to get access to wxWebView, as mentioned in #203 

I then re-installed the erlang version and got no wx related errors.

**Comment by Stratus3D** [comment]
Nice work figuring this out @keshav-c ! So let me see if I can sum things up correctly:

1. You installed Wx on your system and that alone didn't allow you to build Erlang with Wx support.
1. You then found that you needed to select a specific wx-config for your system. This solved the issue you were having.
1. You also had to install `libwxgtk-webview3.0-gtk3-dev` to get wxWebView.
1. Output from `asdf install` was confusing and mentioned kerl and an `activate` command.

There are some things we can do based on your experience to improve things:

* For 2, mention in the docs that you may need to select the correct wx-config for your system.
* For 3, maybe mention that `libwxgtk-webview3.0-gtk3-dev` should be installed if you want `wxWebView` (or maybe not, is there anything in Erlang that requires this?)
* For 4, don't show confusing output from kerl, as these details have been abstracted away by asdf-erlang.

Thoughts?

**Comment by keshav-c** [comment]
Sounds great @Stratus3D :+1: 
I only pursued `3` because of an error I got saying something to the effect of `wxWebView` access would be disabled for your install. I don't know where this would be relevant except for maybe making cross-platform desktop apps using Elixir/Erlang.

For `4`, you would know better as I have no idea what that is :smile:

**Comment by Stratus3D** [comment]
Please take a look at https://github.com/asdf-vm/asdf-erlang/pull/245 @keshav-c and let me know if those changes look good to you.
