### ISSUE TITLE
Erlang installation stuck on MacBook M1PRO

### ISSUE THREAD

**Issue by marinac-dev** [asdf-vm/asdf-erlang#268]
I have a project that uses Erlang 23.2.7.
When I run `asdf install` it gives me this:

```bash
❯ asdf install
elixir 1.11.4-otp-23 is already installed
asdf_23.2.7 is not a kerl-managed Erlang/OTP installation
No build named asdf_23.2.7
Extracting source code
Building Erlang/OTP 23.2.7 (asdf_23.2.7), please wait...
```

It's stuck on last step, I left it overnight and in the morning it wasn't finished building.
I tried re-installing plugin, tried `"--without-javac"` flag but to no avail.

I'm using MacBook Pro 16" with macOS Ventura 13.1, I've been using asdf for over a year and I never saw this issue.

It seems to be stuck on "patch" step w/e that means

**Comment by erickgnavar** [comment]
Had the same issue and it was fixed just pressing `return` after the script got stuck

**Comment by marinac-dev** [comment]
Hmm @erickgnavar that actually worked wow...
Now I'm getting another errors but nothing new, `in6addr_any` error from this [issue](https://github.com/asdf-vm/asdf-erlang/issues/157)
