### ISSUE TITLE
If  compile  failed   it will  redownload the install package

### ISSUE THREAD

**Issue by zhaohansprt** [asdf-vm/asdf-erlang#27]

**Comment by Stratus3D** [comment]
Can you provide more information on this issue? How did you find out it was redownloading the package?

**Comment by rjanja** [comment]
I ran into this today and can provide some additional info:

```
$ asdf install erlang 19.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    373      0 --:--:-- --:--:-- --:--:--   373
100 65.3M  100 65.3M    0     0   338k      0  0:03:17  0:03:17 --:--:--  340k
Building with options: --with-ssl=/usr --prefix=/home/radams/.asdf/installs/erlang/19.3
Ignoring the --cache-file argument since it can cause the system to be erroneously configured
Disabling caching
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... no
checking for cc... no
checking for cc... no
checking for cl... no
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details.
```

I installed the `build-essential` and some other packages, then:
```
$ asdf install erlang 19.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    416      0 --:--:-- --:--:-- --:--:--   415
100 65.3M  100 65.3M    0     0   328k      0  0:03:23  0:03:23 --:--:--  260k
Building with options: --with-ssl=/usr --prefix=/home/radams/.asdf/installs/erlang/19.3
Ignoring the --cache-file argument since it can cause the system to be erroneously configured
Disabling caching
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for gcc... gcc
...[snip]
```

It's a bit of an annoyance to need to download the same file to try again, but it's not a showstopper.

**Comment by chungwong** [comment]
I found as long as you run
`asdf install xxx a.b.c`
**asdf** tends to download everything again instead of reusing the downloaded copy

**Comment by Stratus3D** [comment]
Yes, this is the way asdf plugins typically work. It would be possible to store the downloads in a set location and reuse them again in future installs, but there is the potential for this to cause problems (what if I download an archive of master?), and I'm not sure it's worth the effort since most installs should be successful.

**Comment by chungwong** [comment]
I cannot answer "is it worth doing it". 

However, I am an unlucky man and I am on my second day trying to get erlang installed on a server. Every time I start fresh, it costed 5 - 6 minutes to download erlang. The compiling time itself is already time consuming, while not adding 5-6 minutes for those unlucky men will be helpful though.

**Comment by zhaohansprt** [comment]
i guess  the  key point is the version describe (19.3) should have more number(may be the git reversion code) in the background to tell the  detailed patch updates , store them as key  with the package and checksum ;for furture compare to skip the download ,like the kerl does
