### ISSUE TITLE
not able to download kerl script using curl 

### ISSUE THREAD

**Issue by anew-bhav** [asdf-vm/asdf-erlang#271]
while trying to install an erlang version, kerl is dependent. 
The plugin manages to install kerl on its own. but somehow today, the URL `https://raw.githubusercontent.com/kerl/kerl/master/kerl` did not respond

So kerl installation (asdf erlang installation pretask) hung up. 

There should be a way to look for and already installed kerl and use that instead.

**Comment by anew-bhav** [comment]
I was able to work around this, down kerl script by cloning  [here](https://github.com/kerl/kerl) and putting the kerl script inside ~/.asdf/plugins/erlang

**Comment by Stratus3D** [comment]
Hi @anew-bhav , it's working for me now. I'm guessing there was an intermittent issue with the Github servers. I'm going to close this issue. If you have reason to suspect this was due to a bug in asdf-erlang please let me know.
