### ISSUE TITLE
`kerl cleanup` not actually running?

### ISSUE THREAD

**Issue by jimsynz** [asdf-vm/asdf-erlang#280]
I notice that `bin/install` does actually call `kerl cleanup` after successful install, however I think it must be calling it with the incorrect environment or something because when I do a fresh install of Erlang 26.0.2 I have over 700MB of files sitting in `.asdf/plugins/erlang/kerl-home/builds/asdf_26.0.2/otp_src_26.0.2`.

You can reproduce it like so:

```
docker pull code.harton.nz/james/asdf_container:latest
docker run --rm -it code.harton.nz/james/asdf_container:latest
$ asdf plugin add erlang
$ asdf install erlang latest
$ du -shc .asdf/plugins/erlang/kerl-home/builds/asdf_26.0.2
738M	.asdf/plugins/erlang/kerl-home/builds/asdf_26.0.2
738M	total
$ KERL_BASE_DIR=.asdf/plugins/erlang/kerl-home .asdf/plugins/erlang/kerl cleanup asdf_26.0.2 
Cleaning up compilation products for asdf_26.0.2
Cleaned up compilation products for asdf_26.0.2 under .asdf/plugins/erlang/kerl-home/builds
$ du -shc .asdf/plugins/erlang/kerl-home/builds/asdf_26.0.2
du: cannot access '.asdf/plugins/erlang/kerl-home/builds/asdf_26.0.2': No such file or directory
0	total
```

Let me know if there's any way I can further help debug this.

**Comment by Stratus3D** [comment]
I think I figured out the problem here. I will create a PR for this tomorrow.
