### ISSUE TITLE
Using HTTPS on Github vs HTTP connection to download from Erlang Solutions

### ISSUE THREAD

**Issue by zph** [asdf-vm/asdf-erlang#31]
First off, thank you for making this plugin available for erlang version management! 🌝

I was browsing through the source code of the plugin and notice that there are two code pathways, determined by the $version variable.

In one pathway, when $version = "version", we fetch data from http endpoint. Otherwise it's fetched by ref on Github over HTTPS.

I see that Github has the version releases for OTP available. Since Erlang solutions redirects from HTTPS -> HTTP (if trying to use HTTPS), what about using the https releases from Github as the source of truth?

From browsing source on github.com/erlang/otp, it appears that Erlang solutions folks are heavily involved (run?) that repository. Could we trust the releases there over HTTPS instead of from the HTTP endpoint?

**Comment by Stratus3D** [comment]
@zph I think that's a good idea. I haven't checked Github, but assuming all the releases available from Erlang Solutions are on Github I think it would be a good change to make.

**Comment by zackehh** [comment]
Perhaps using GitHub means that the `list-all` could be automatic, rather than hardcoded, too.

**Comment by aeons** [comment]
Another plus is that the github releases include patch releases.

**Comment by bryanhuntesl** [comment]
Can I get more information please about Erlang Solutions redirecting from HTTPS -> HTTP. 

TBH I got a bit worried when I read this but was unable to reproduce:

```
% curl -L -vvvv https://packages.erlang-solutions.com/erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_18.1-1~ubuntu~precise_amd64.deb > /tmp/out                            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 31.172.186.53...                                                     
* TCP_NODELAY set                      
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to packages.erlang-solutions.com (31.172.186.53) port 443 (#0)      * TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_GCM_SHA384                 
* Server certificate: *.erlang-solutions.com                                   
* Server certificate: Go Daddy Secure Certificate Authority - G2               
* Server certificate: Go Daddy Root Certificate Authority - G2                 
> GET /erlang/esl-erlang/FLAVOUR_1_general/esl-erlang_18.1-1~ubuntu~precise_amd64.deb HTTP/1.1                                                                
> Host: packages.erlang-solutions.com  
> User-Agent: curl/7.54.0              
> Accept: */*                          
>                                      
< HTTP/1.1 200 OK                      
< Date: Thu, 19 Oct 2017 10:13:35 GMT  
< Server: Apache                       
< Last-Modified: Wed, 23 Sep 2015 11:52:08 GMT                                 
< ETag: "1c05f4-30942a4-52068be7dfb2e" 
< Accept-Ranges: bytes                 
< Content-Length: 50938532             
< Access-Control-Allow-Origin: *       
< Content-Type: application/x-debian-package                                   
<                                      
{ [16384 bytes data]                   
 11 48.5M   11 5552k    0     0  2422k      0  0:00:20  0:00:02  0:00:18 2422k 
100 48.5M  100 48.5M    0     0  3174k      0  0:00:15  0:00:15 --:--:-- 2845k 
* Connection #0 to host packages.erlang-solutions.com left intact              

```

Would you be able to run the same with `curl -L -vvvv ...` and I'll take it to our operations team. 

Thanks,

Bryan

**Comment by Stratus3D** [comment]
Can you all upgrade to the latest version of asdf-erlang and try this again? I did a major refactor and replaced all our code with calls to kerl, the other Erlang version manager. This means we can leverage all the great work done by the kerl contributors without losing the benefits of asdf. I believe we have kerl configured to pull everything form GitHub over HTTPS.

If you are still able to reproduce this issue please open an issue on the kerl repository: https://github.com/kerl/kerl
