### ISSUE TITLE
Interrupted downloads are being treated as complete installs

### ISSUE THREAD

**Issue by tuvistavie** [asdf-vm/asdf-erlang#39]
Moved from asdf-vm/asdf#214 by @seleem1337 
---

If you start installing a version of a language (e.g. Erlang) and for some reason it gets interrupted (e.g. Ctrl-C), it will be treated as a complete installation, meaning:

$ asdf install erlang 20.0
erlang 20.0 is already installed
But

$ iex
No such command in 20.0 of erlang
And .asdf/installs/erlang/20.0/ path is empty.

The workaround is simple: uninstall erlang and reinstall it again but that's not ideal unless you are previously aware of this issue.

**Comment by Stratus3D** [comment]
https://github.com/asdf-vm/asdf-erlang/blob/master/bin/install#L145 is the culprit I believe. However, I think the subshell here https://github.com/asdf-vm/asdf-erlang/blob/master/bin/install#L19 may not be handling errors properly either.

**Comment by tuvistavie** [comment]
Indeed, we need to check the return value of `download_source`.
Adding `|| exit 1` here should be enough I think. https://github.com/asdf-vm/asdf-erlang/blob/master/bin/install#L15
The subshell being the last thing we do in the install command, if it fails the error should be propagated correctly.

**Comment by tuvistavie** [comment]
Actually I just realized we should not be using `exit` but `return` in all calls.
We do want the error to propagate to `asdf`, not to exit.
