### ISSUE TITLE
Digest Update / boringssl compile error on MacOS 10.13 Beta 17A264c

### ISSUE THREAD

**Issue by salimane** [asdf-vm/asdf-erlang#40]
On the new macOS High Sierra

```shell
salimane at Salimanes-MacBook-Pro (git:salimane.com)  in ~/src/project
± cat .tool-versions                                          
erlang 20.0
elixir 1.5.1
nodejs 6.11.2

salimane at Salimanes-MacBook-Pro (git:salimane.com)  in ~/src/project
± asdf install                                                
erlang 20.0 is already installed
elixir 1.5.1 is already installed
nodejs 6.11.2 is already installed

salimane at Salimanes-MacBook-Pro (git:salimane.com)  in ~/src/project
± mix local.hex                                               
Assertion failed: (ctx), function digest_update, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/boringssl/boringssl-109.1.5/apple/crypto/digests.c, line 49.
zsh: abort      mix local.hex

```

The issue is well described [here](https://github.com/elixir-lang/elixir/issues/6200)

There is already a fix in [homebrew core](https://github.com/Homebrew/homebrew-core/pull/15297)

Thanks

**Comment by tmepple** [comment]
The fix is merged in Erlang 20.1 which hopefully is released in the next few weeks.  Until then I have just uninstalled all asdf Erlang versions and installed the latest homebrew version as you mentioned which is working on High Sierra GM seed.  Not ideal but it's simple and works great.

**Comment by benwilson512** [comment]
FYI OTP 20.1 is officially out.

**Comment by bryanstearns** [comment]
... and there's a PR to add it! https://github.com/asdf-vm/asdf-erlang/pull/43

**Comment by linjunpop** [comment]
You can also run `asdf install erlang 20.1` to install 20.1 now.

**Comment by kzemek** [comment]
Erlang 19 seems to have the same problem. While the fix is merged in 20.1 and for homebrew `erlang` package, I use asdf specifically to maintain multiple versions of Erlang for development purposes.

**Comment by jtomaszewski** [comment]
We'd need to do sth like this https://github.com/Homebrew/homebrew-core/pull/15297/commits/e3a9e39a6736deaf7b2e5ae7e976bcf724d28610 in here to make it work on older versions.

**Comment by Stratus3D** [comment]
We've since switched to https://github.com/kerl/kerl for Erlang builds, so this hopefully shouldn't be a problem anymore.
