### ISSUE TITLE
Support installing patch versions of Erlang

### ISSUE THREAD

**Issue by enilsen16** [asdf-vm/asdf-erlang#48]
```
~ asdf install erlang 20.1.1
** Resuming transfer from byte position 291
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   178  100   178    0     0    312      0 --:--:-- --:--:-- --:--:--   313
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
```

I'm not sure if Erlang Solutions provides these, but we should be able to download them from github and then install it. 

Possibly related to #31

**Comment by HashNuke** [comment]
@enilsen16 We already support it. You can do the following:

`asdf install erlang ref:OTP-20.1.2`

Where `OTP-20.1.2` is a valid tag that you can find on https://github.com/erlang/otp/releases. You can also specify a commit sha or branch name if you insist on the latest super-powers.

**Comment by shanesveller** [comment]
This workaround syntax no longer works after #54 merged - has anyone figured out the `kerl`-based alternative? This issue seems pertinent: https://github.com/kerl/kerl/issues/240
