### ISSUE TITLE
Unable to install erlang on Ubuntu

### ISSUE THREAD

**Issue by HDT186** [asdf-vm/asdf-erlang#49]
### Issue

I tried to install erlang 20.1 which ended in a:
.asdf/plugins/erlang/bin/install: line 40: ./configure: Permission denied

The problem is, the install script makes a tmp directory (mktemp -d -t erlang_build_XXXXXX) in /tmp. But /tmp is mounted as noexec, which results in a "Permission denied".
Two workarounds:
- $ sudo mount -o remount,exec /tmp
or
- use $TMPDIR (e.g. $ export TMPDIR=$HOME/erlang_tmp)

Please fix this.

### Environment

**OS**: Ubuntu 16.04.3 LTS

**asdf version**: v0.4.0

**Comment by Stratus3D** [comment]
The temp dir route is probably the best and easiest option here. I almost wonder if the temp directory logic is something that we should keep in asdf. We could just pass the path to the temp directory to all the plugins, and the plugins that needed it would use it. asdf would then remove the temp directory after the installation completed.

**Comment by HDT186** [comment]
Actually the noexec mount option for /tmp is not a part of Ubuntu but from Debian. I added it for enhanced security. So it should be at least an issue for Debian. Maybe change to header from Ubuntu to Debian.

**Comment by Stratus3D** [comment]
@HDT186 can you upgrade to the latest version of asdf-erlang and try this again? I did a major refactor and replaced all our code with calls to kerl, the other Erlang version manager. This means we can leverage all the great work done by the kerl contributors without losing the benefits of asdf.

If you are still able to reproduce this issue please open an issue on the kerl repository: https://github.com/kerl/kerl
