### ISSUE TITLE
can't install erlang 20.1 on MacOSX 10.11.6

### ISSUE THREAD

**Issue by philosodad** [asdf-vm/asdf-erlang#50]
In file included from /var/folders/cm/crhcj_ys6fb7_4ntpqy5qlc80000gn/T/otp_src_20.1/erts/emulator/pcre/pcre_exec.c:6462:
/var/folders/cm/crhcj_ys6fb7_4ntpqy5qlc80000gn/T/otp_src_20.1/erts/emulator/pcre/pcre_exec_loop_break_cases.inc:32:6: error: expected expression
case : goto L_LOOP_COUNT_5974;
     ^
1 error generated.
make[4]: *** [/var/folders/cm/crhcj_ys6fb7_4ntpqy5qlc80000gn/T/otp_src_20.1/erts/emulator/pcre/obj/x86_64-apple-darwin15.6.0/opt/pcre_exec.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [opt] Error 2
make[2]: *** [opt] Error 2
make[1]: *** [smp] Error 2
make: *** [emulator] Error 2
$

**Comment by Stratus3D** [comment]
I think I ran into this same issue earlier this year. From my notes:

```
# Make sure we are using vanilla grep
# http://erlang.org/pipermail/erlang-questions/2014-April/078526.html
# https://github.com/kerl/kerl/pull/99
unlalias grep
export GREP_OPTIONS=""
export GREP_COLOR=""
export GREP_COLORS=""
```

The post on the mailing list was particularly helpful: http://erlang.org/pipermail/erlang-questions/2014-April/078526.html

**Comment by Stratus3D** [comment]
We are considering moving to kerl (#53), if we do this should become even easier and no grep hacks should be needed. 

Please reopen this issue if my earlier comment doesn't solve your problem.
