### ISSUE TITLE
Can’t uninstall versions installed without kerl

### ISSUE THREAD

**Issue by ejpcmac** [asdf-vm/asdf-erlang#56]
When I run `asdf uninstall erlang 20.2` for instance, i get:

    No build named asdf_20.2

I think that’s because `asdf` calls `kerl` here, where it should also check for an asdf build.

**Comment by ejpcmac** [comment]
@Stratus3D As you know better than me how `asdf` works: does it know the list of all installed Erlang versions without calling `kerl`? If yes maybe we can:

1. check if the version is installed,
2. if the version is not installed at all, report an error,
3. if it is installed, try to uninstall it with `kerl`, but keep errors quiet (maybe),
4. even if the `kerl` uninstall have failed, let the script call the `rm -rf` at the end:

https://github.com/asdf-vm/asdf-erlang/blob/374f93aaba3695283b2b55e9eec08b9ee9127053/bin/uninstall#L11

**Comment by CraigCottingham** [comment]
@ejpcmac I didn't have `kerl` installed until today, and `asdf list erlang` has been working without it.

Now that I have installed `kerl`, I'm installing an old version of Erlang so I can try uninstalling it, and see if I still get this error.

**Comment by ejpcmac** [comment]
@CraigCottingham To reproduce the initial bug, you need an Erlang version installed with an old `asdf` version, not using `kerl`. This is when trying to uninstall such version with the new `asdf` version using `kerl`:

* `kerl delete build` tries to delete the build, but logically it does not exist because the Erlang version was installed without `kerl`
* `kerl delete build` logs the error and its return status is not 0
* `set -e` being put at the beginnig of the uninstall script, the uninstall scripts stops here and does not deletes the given Erlang version.

Unsetting `-e`, we get:

* `kerl delete build` complains about the unknown build
* `kerl delete installation` complains about the unknown installation
* `rm -rf` deletes the installation correctly, and `asdf list erlang` does not show the version anymore

**Comment by CraigCottingham** [comment]
@ejpcmac I'm ahead of you on this one. 😄 

1. I commented out `set -e` and was able to successfully uninstall an old version of Erlang.
2. I installed `kerl` via homebrew and installed an old version of Erlang.
3. I uncommented `set -e`, and was able to successfully uninstall the old version of Erlang again.

The documentation says that it will use its own install of `kerl` if you don't already have it, but that doesn't appear to be the case. Maybe my `asdf-erlang` plugin is out of date?

**Comment by CraigCottingham** [comment]
Okay, I thought I had tried installing and uninstalling since upgrading my plugin, but apparently not. I just went through the whole process without an external install of `kerl` and with `set -e` enabled in the uninstall script, and it works fine.

**Comment by ejpcmac** [comment]
Yes, with `set -e` it works fine as long as you try to uninstall a version installed with the last `asdf-erlang` version. That’s just for versions installed with the old installer there is a problem.

**Comment by Stratus3D** [comment]
You both are right about `set -e`. It causes the script to terminate when an error is encountered, and an error does occur when kerl tries to remove an installation it didn't install.

I think the proper solution to this is to check if kerl actually installed the given installation, and if so use kerl to uninstall (otherwise kerl will think it's still installed even after the directory is removed). I've created a PR that checks if kerl installed the version, and if so uses kerl to uninstall it. It then does `rm -rf` on the directory it was installed to regardless of how that version was install. This should handle both cases.
