### ISSUE TITLE
Skip dependency on Java when installing?

### ISSUE THREAD

**Issue by CraigCottingham** [asdf-vm/asdf-erlang#58]
Is it possible to pass options to whatever is installing Erlang to not try to do the things that depend on Java? I don't have it installed (macOS 10.13.2), and while the two alerts that pop up suggesting that I install it are merely an annoyance, I'd rather not have them pop up at all.

**Comment by miltonArango** [comment]
Yes, you can. Inside the `.asdf/plugins/erlang/kerl-home/` create a .kerlrc file and pass this configuration options:

(In the .kerlrc file)
`KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"` 

For more information check the kerl GitHub docs:
[Kerl](https://github.com/kerl/kerl#tuning)

**Comment by Stratus3D** [comment]
Yes, what @miltonArango said should work. You should also be able to do this on the fly using the same environment variable in the shell:
```
export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
asdf install erlang <version>
```

**Comment by BryanJBryce** [comment]
What does `--disable-debug` have to do with Java?

**Comment by Stratus3D** [comment]
@BryanJBryce not sure why I included that. Looking at the latest version of kerl I don't see that flag referenced anywhere, so it doesn't seem like it is even supported.
