### ISSUE TITLE
[linux] Cryptic warning during install about missing package ''

### ISSUE THREAD

**Issue by mhanberg** [asdf-vm/asdf-erlang#62]
On linux, when you attempt to install (in this case v20.2.2) Erlang, you get the warning `WARNING: It appears that a required development package ' ' is not installed`

Any idea what this means?

**Comment by Stratus3D** [comment]
https://github.com/kerl/kerl/issues/245

**Comment by mhanberg** [comment]
Thanks!

**Comment by ukazap** [comment]
did you manage to get it installed? i have no luck with 20.2.4

**Comment by goravbhootra** [comment]
kerl 1.8.2 has been released fixing the issue

**Comment by jimmay5469** [comment]
I had the same issue, uninstalling java from my system seems to have fixed it so if you don't need java it might be worth giving that a try.
