### ISSUE TITLE
Install not possible after uninstall

### ISSUE THREAD

**Issue by cehoffman** [asdf-vm/asdf-erlang#64]
There are artifacts from a previous install that prevents new installs from succeeding.

```sh
$ asdf install erlang 20.2.4
$ asdf uninstall erlang 20.2.4
$ asdf install erlang 20.2.4
There's already a build named asdf_20.2.4
```

This is because the files `otp_builds` and `otp_installations` in kerl-home contain entries for the `asdf_20.2.4` install that need to be removed before a reinstall can occur.

**Comment by dimitarvp** [comment]
You saved me a lot of headache. I wasted an hour fighting with this until I realised I was searching for the version with the wrong regex and _then_ I stumbled upon this issue.

Thanks!

**Comment by alanvardy** [comment]
Thank you @cehoffman 

To elaborate for anyone stumbling across this, you can use:
`nano ~/.asdf/plugins/erlang/kerl-home/otp_builds`
and delete the offending build entry.

**Comment by pedroassumpcao** [comment]
Thanks @cehoffman and @alanvardy
