### ISSUE TITLE
Ubuntu WSL 16.04 cannot Install erlang

### ISSUE THREAD

**Issue by sgnd** [asdf-vm/asdf-erlang#68]
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Building Erlang/OTP 20.0 (asdf_20.0), please wait...
/home/suganda/.asdf/plugins/erlang/kerl: 715: cd: can't cd to /home/suganda/.asdf/plugins/erlang/kerl-home/builds/asdf_20.0/otp_src_20.0

**Comment by Stratus3D** [comment]
It looks like something went wrong with the archive it downloaded. Did you try installing another Erlang version? With that output it's impossible to say what the problem was.

**Comment by sgnd** [comment]
I try installing erlang 20.3 works, thank you!
