### ISSUE TITLE
Erlang installation gets stuck on building kerl on new Ubuntu EC2 instance

### ISSUE THREAD

**Issue by jayprado** [asdf-vm/asdf-erlang#84]
I can't seem to finish the installation of `erlang 20.1` through `asdf` on a new `Ubuntu 16.04` EC2 instance on AWS. On a newly launched instance, I run `apt-get update` & `apt-get upgrade` before I install `asdf` along with the dependencies listed under the **Ubuntu** entry [here](https://github.com/asdf-vm/asdf#setup).

The installation always end up getting stuck on the part where it says `Using fakefop to generate placeholder PDF files.`

I have tried installing a Java compiler but it made no difference.

I also tried installing `erlang` using `kerl` (and not `asdf`) but it gets stuck on the same place.

I am very new to all of these so any help would be very much appreciated.

**Comment by Stratus3D** [comment]
Were you using the latest version of asdf-erlang? We recently made some changes to the way documentation is built and installed. Latest on the master branch shouldn't install any docs unless you tell it to.

**Comment by jayprado** [comment]
Hi @Stratus3D, yes. I installed `asdf-erlang` using `asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git`, which I assume installs the latest version.

**Comment by Stratus3D** [comment]
For good measure run`asdf plugin-update erlang` and see if it pulls down any new changes.

I use Ubuntu on my laptop and I have not had any trouble recently. When it gets stuck is that message all you see? And does it just hang or does it crash?

**Comment by Ciboulette** [comment]
I have this error on ubuntu 16.04 Xenial EC2 when i want to building erlang/OTP 20.3
`make[3]: *** [x86_64-unknown-linux-gnu/wxe_funcs.o] Error 4`

**Comment by jayprado** [comment]
@Stratus3D It says it's already the latest version. Still gets stuck on this part. Wonder what could be the cause?

![image](https://user-images.githubusercontent.com/1752354/45919177-3d882480-bec4-11e8-9730-59a1606d6c6f.png)

**Comment by lpil** [comment]
What's the CPU usage? I thought my build was stuck at this point but it seems it is compiling, just it prints nothing during this process.

**Comment by tuvokki** [comment]
I did the following on Ubuntu 16.04 with all relevant packages installed:
```
asdf plugin-remove erlang
asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
asdf plugin-update erlang
asdf install erlang 21.1
```
It took pretty long (about 15 minutes) but it worked ok.

**Comment by x-ji** [comment]
Seems to have the same situation under a DigitalOcean Ubuntu VM. It actually finished in the end but it just took very long.

**Comment by Stratus3D** [comment]
I'm going to close this since I don't think this is an issue with asdf-erlang. Erlang compilation takes time. I don't think it's ever taken less than 10 minutes for me on top of the line hardware. I can imagine it taking an hour or more on VM a sharing a CPU with other VMs.
