### ISSUE TITLE
Installing Erlang on OSX Mojave can't find OpenSSL 

### ISSUE THREAD

**Issue by fhunleth** [asdf-vm/asdf-erlang#86]
I'm currently getting:

```sh
$ asdf install erlang 21.0.9
Extracting source code
Building Erlang/OTP 21.0.9 (asdf_21.0.9), please wait...
APPLICATIONS DISABLED (See: /Users/fhunleth/.asdf/plugins/erlang/kerl-home/builds/asdf_21.0.9/otp_build_21.0.9.log)
 * crypto         : No usable OpenSSL found
 * odbc           : ODBC library - header check failed
 * ssh            : No usable OpenSSL found
 * ssl            : No usable OpenSSL found
```

I've tried reinstalling OpenSSL with Homebrew and then exporting PKG_CONFIG_PATH, CPPFLAGS, and LDFLAGS to help the build tools find it, but no luck.

I'm at the tip revisions of asdf-erlang and asdf.

I'm wondering if there's anything else that would be good to try. As far as I could tell installing Erlang w/ asdf on High Sierra worked flawlessly for me, so I assume that the Mojave upgrade changed something important.

**Comment by MarcusSky** [comment]
same here!

**Comment by MarcusSky** [comment]
@fhunleth there's a possible solution here: https://github.com/asdf-vm/asdf-erlang/issues/82 I'm trying it out right now.

**Comment by sirn** [comment]
Kerl detects if it is being installed on macOS 10.11+ and use `brew` to determine the `openssl` location. Unfortunately the detection is limited to just 10.13 (High Sierra) and OpenSSL detection doesn't happen in Mojave.

I've went ahead and [created PR](https://github.com/kerl/kerl/pull/301) for Kerl to detect OpenSSL on Mojave. If you want to use `kerl` to install Erlang in the same manner as `asdf-erlang`, please try:

```
$ export ERLANG_VERSION=21.0.9
$ curl -o kerl https://raw.githubusercontent.com/kerl/kerl/ea951d4dfd10e5b80f8a7a1bc7a56062fd426907/kerl
$ chmod +x kerl
$ KERL_BUILD_BACKEND=git KERL_BASE_DIR="$HOME/.asdf/plugins/erlang/kerl-home/" ./kerl build $ERLANG_VERSION asdf_$ERLANG_VERSION
$ ./kerl install asdf_$ERLANG_VERSION ~/.asdf/installs/erlang/$ERLANG_VERSION/
```

**Comment by Stratus3D** [comment]
For anyone who comes across this issue. The fix should be as simple as running `$ asdf plugin-update erlang`.

**Comment by coladarci** [comment]
Thanks @Stratus3D for pointing me in the right direction - `asdf plugin-update --all` is a good thing to do after upgrading to Mojave, we've found..

**Comment by pdgonzalez872** [comment]
If folks run into this issue and `asdf plugin-update erlang` does not solve their problem:

After helping set up a colleague's machine, using the `--with-ssl` flag, as seen here: https://github.com/asdf-vm/asdf-erlang/issues/82#issuecomment-415930974 was the solution.

**Comment by skyerus** [comment]
To add to this if you're still having issues, I had to `rm -R ~/.asdf/plugins/erlang/kerl-home/builds/asdf_19.0` to get it to install properly
