### ISSUE TITLE
[BUG] Error prevents WxWdigets from working with Erlang 21.1

### ISSUE THREAD

**Issue by chintan-mishra** [asdf-vm/asdf-erlang#90]
While installing Erlang 21.1 on fresh Fedora 28 installation I receive the error stated below.

`No OpenGL headers found, wx will NOT be usable`

However, when I installed Erlang 21.0.9 this issue is not there.

I installed all the necessary required packages mentioned in the README.

**Comment by Stratus3D** [comment]
This sounds like a kerl issue. Please report an issue to https://github.com/kerl/kerl/issues if you do not see an existing issue. Could this be related? https://github.com/kerl/kerl/issues/294
