### ISSUE TITLE
Unable to compile 21.1 with wx on Debian stretch

### ISSUE THREAD

**Issue by lpil** [asdf-vm/asdf-erlang#91]
I've installed all the packages listed in the README (and a few other for good measure) yet I am still unable to compile with wx support. (Though libpng3 isn't available so I installed everything with the libpng prefix)

> For building with wxWidgets (start observer or debugger!) apt-get -y install libwxgtk3.0-dev libgl1-mesa-dev libglu1-mesa-dev libpng3

```
APPLICATIONS INFORMATION (See: /home/louispilfold/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_build_21.1.log)
 * wx             : wxWidgets not found, wx will NOT be usable
```

Is there a way to determine what package I'm missing?

**Comment by Stratus3D** [comment]
This looks similar to #90. You'll probably get this solved faster over at https://github.com/kerl/kerl.

Maybe related to https://github.com/kerl/kerl/issues/279#issuecomment-386664790?

**Comment by jerko-culina** [comment]
```
make[3]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/src'
make[3]: Entering directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/c_src'
 CC     x86_64-unknown-linux-gnu/wxe_driver.o
 CC     x86_64-unknown-linux-gnu/wxe_ps_init.o
 CXX    x86_64-unknown-linux-gnu/wxe_main.o
 CXX    x86_64-unknown-linux-gnu/wxe_impl.o
 CXX    x86_64-unknown-linux-gnu/wxe_helpers.o
 CXX    x86_64-unknown-linux-gnu/wxe_callback_impl.o
 CXX    x86_64-unknown-linux-gnu/wxe_return.o
 CXX    x86_64-unknown-linux-gnu/wxe_gl.o
 CXX    x86_64-unknown-linux-gnu/wxe_funcs.o

cc1plus: out of memory allocating 54634528 bytes after a total of 1361604608 bytes
Makefile:156: recipe for target 'x86_64-unknown-linux-gnu/wxe_funcs.o' failed
make[3]: *** [x86_64-unknown-linux-gnu/wxe_funcs.o] Error 1
make[3]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/c_src'
/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[2]: *** [opt] Error 2
make[2]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx'
/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/make/otp_subdir.mk:29: recipe for target 'opt' failed
make[1]: *** [opt] Error 2
make[1]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib'
Makefile:482: recipe for target 'libs' failed
make: *** [libs] Error 2
```
on ubuntu 18.04 got error above

**Comment by khipukamayuq** [comment]
@lpil Wondering what you know about libpng3 not existing. I'm on Ubuntu 18.10 and get `E: Unable to locate package` when trying to install it per asdf-erlang's README. Can't find much on it. Did see a libpng at version 1.6.36. Does that work instead of libpng3 maybe? Sorta fumbling in the dark here.

**Comment by Stratus3D** [comment]
@khipukamayuq related: https://github.com/asdf-vm/asdf-erlang/pull/98

**Comment by designrubenz** [comment]
> ```
> make[3]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/src'
> make[3]: Entering directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/c_src'
>  CC     x86_64-unknown-linux-gnu/wxe_driver.o
>  CC     x86_64-unknown-linux-gnu/wxe_ps_init.o
>  CXX    x86_64-unknown-linux-gnu/wxe_main.o
>  CXX    x86_64-unknown-linux-gnu/wxe_impl.o
>  CXX    x86_64-unknown-linux-gnu/wxe_helpers.o
>  CXX    x86_64-unknown-linux-gnu/wxe_callback_impl.o
>  CXX    x86_64-unknown-linux-gnu/wxe_return.o
>  CXX    x86_64-unknown-linux-gnu/wxe_gl.o
>  CXX    x86_64-unknown-linux-gnu/wxe_funcs.o
> 
> cc1plus: out of memory allocating 54634528 bytes after a total of 1361604608 bytes
> Makefile:156: recipe for target 'x86_64-unknown-linux-gnu/wxe_funcs.o' failed
> make[3]: *** [x86_64-unknown-linux-gnu/wxe_funcs.o] Error 1
> make[3]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx/c_src'
> /home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/make/otp_subdir.mk:29: recipe for target 'opt' failed
> make[2]: *** [opt] Error 2
> make[2]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib/wx'
> /home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/make/otp_subdir.mk:29: recipe for target 'opt' failed
> make[1]: *** [opt] Error 2
> make[1]: Leaving directory '/home/deploy/.asdf/plugins/erlang/kerl-home/builds/asdf_21.1/otp_src_21.1/lib'
> Makefile:482: recipe for target 'libs' failed
> make: *** [libs] Error 2
> ```
> on ubuntu 18.04 got error above
> 
> UPDATE:
> memory leak cause this problem, so after I added 4 GB of swap space, it builds without any problem, it was happened on Digital Ocean droplet 1vcpu 2gb

Second this!
A 2GB Digital Ocean droplet running on Ubuntu 18.04 produced the exact same error message. Had to resize the droplet to 4GB and voila, works just fine.

I find some tutorials out there misleading as they explicitly mention 1GB or 2GB droplets.

Thanks a lot to @jerko-culina for his update!

**Comment by Stratus3D** [comment]
Closing since it I do not believe there are any bugs in asdf-erlang contributing to these problems.
